textRange: 200+
textDesc: {}
group: weight
threshold: 200
icon: s_icon_l32_unit_mass5
valuesWeight:
  stabilityBonus: 12
  concussionMultiplier: 0
  hoverAltitudeFactor: 0
  bulldozeHitDestabilization: 0
  crashHitDestabilization: 0
