textRange: ''
textDesc: {}
group: weight
threshold: -1
icon: s_icon_l32_unit_mass1
valuesWeight:
  stabilityBonus: -1
  concussionMultiplier: 1.5
  hoverAltitudeFactor: 0.5
  bulldozeHitDestabilization: 0.2
  crashHitDestabilization: 0.2
