textRange: ''
textDesc: {}
group: weight
threshold: 6
icon: s_icon_l32_unit_mass2
valuesWeight:
  stabilityBonus: 1
  concussionMultiplier: 1
  hoverAltitudeFactor: 0.5
  bulldozeHitDestabilization: 0.2
  crashHitDestabilization: 0.15
