timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: 레벨 테스트
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: 계약
    textEng: Contracts
  replay__name:
    id: 2
    text: 캠페인
    textEng: Campaign
  training__name:
    id: 2
    text: 교육
    textEng: Training
