timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: 쉬운 계약
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: 중간 난이도 계약
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: 어려운 계약
    textEng: Challenging contract
