timeLastSync: 63817556069
entries:
  base_briefing_list__s0:
    id: 2
    text: 분대로 돌아가기
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: 추가 혹은 제거
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: 목록 입력
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: 슬롯 비우기
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: 다음 시나리오로 돌아가기
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: 목록으로 이동
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: 다중 선택
    textEng: Multi-select
  base_general__header:
    id: 1
    text: 이동식 기지
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: 조종사, 유닛, 인벤토리를 관리하세요. 자원을 작업장 프로젝트 혹은 기지 업그레이드에 투자하세요. 캠페인을 계속할 준비가 되면 오버월드 맵으로 돌아오세요.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: 탐색
    textEng: Navigate
  base_general__s3:
    id: 1
    text: 월드 맵
    textEng: World map
  base_general__s4:
    id: 1
    text: 조종사 목록
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: 유닛 목록
    textEng: Unit list
  base_general__s6:
    id: 1
    text: 인벤토리
    textEng: Inventory
  base_general__s7:
    id: 1
    text: 작업장
    textEng: Workshop
  base_general__s8:
    id: 1
    text: 업그레이드
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: 목록으로 돌아가기
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: 카테고리 선택
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: 카테고리 열기
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: 이동
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: 아이템 선택하기
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: 상황 메뉴
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: 탐색
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: 상징 색 켜기/끄기
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: 슬롯 비우기
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: 이동
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: 아이콘 선택하기
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: 슬롯 선택하기
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: 슬롯 열기
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: 슬롯 비우기
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: 아이템 선택하기
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: 장비하기
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: 슬롯으로 돌아가기
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: 필터 적용하기
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: 업그레이드 그리드 탐색 중
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: 스크롤
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: 업그레이드 간 이동
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: 능력치로 이동
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: 사이드바에 초점 맞춤
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: 업그레이드로 돌아가기
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: 능력치 선택
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: 방향 바꾸기
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: 타겟 모드
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: 높이 살짝 조정
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: 대화 건너뛰기
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: 탐색에 초점 맞춤
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: 유닛 선택
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: 시간 변경
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: 타임라인에 초점 맞춤
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: 작업 삭제
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: 작업 드래그
    textEng: Drag action
  combat_general__header:
    id: 1
    text: 전투
    textEng: Combat
  combat_general__overview:
    id: 1
    text: 오른쪽 상단 모서리에 있는 목표를 따라 전투에서 이기세요. 예측되는 적의 행동을 검토하고, 타임라인을 이용해 당신의 유닛에 명령을 내리고, 실행해서 계획이 전개되는 모습을 지켜보세요.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: 뒤로 가기 / 취소하기
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: 확정 / 실행
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: 슬로 모션 켜기/끄기
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: 탐색
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: 카메라 이동
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: 카메라 회전
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: 다음 유닛 선택
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: 이전 유닛 선택
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: 타겟팅 모드
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: 작업 선택
    textEng: Select action
  combat_general__s9:
    id: 2
    text: 기간 설정
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: 슬로 모션 켜기/끄기
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: 시간 조절에 초점 맞추기
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: 실행
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: 실행
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: 타임라인으로 이동
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: 작업으로 이동
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: 이동으로 이동
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: 작업 제거
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: 카메라 줌
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: 유닛 전환
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: 세부 사항 켜기/끄기
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: 세부 사항 표시
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: 테스트 줌
    textEng: Zoom test
  credits__s0:
    id: 2
    text: 나가기
    textEng: Exit
  credits__s1:
    id: 2
    text: 스크롤
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: 애니메이션 건너뛰기
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: 확정하기
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: 되돌아가기
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: 지방 선택
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: 맵 이동
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: 옵션 선택
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: 모디파이어 점검
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: 스크롤
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: 오버월드
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: 맵을 탐색하고, 이벤트에 참여하고, 적 땅을 공격하세요. 지방에서 경쟁하고 침략군을 몰아내세요. 이동식 기지를 이용해 유닛, 조종사, 업그레이드를 관리하세요.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: 탐색
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: 맵에서 선택
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: 기지 이동
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: 카메라 이동
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: 카메라 회전
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: 일시 중지 켜기/끄기
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: 옵션 선택
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: 확정
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: 선택
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: 이동
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: 되돌아가기
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: 이동
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: 되돌아가기 / 멈추기
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: 시간 멈춤/흐름
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: 선택
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: 옵션 선택
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: 옵션 변경
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: 프리셋 선택
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: 프리셋 적용
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: 옵션으로 이동
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: 그룹 선택
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: 그룹 입력
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: 옵션 종료
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: 옵션 선택
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: 바인딩 선택
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: 적용 혹은 초기화
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: 그룹으로 돌아가기
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: 바인딩 변경
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: 되돌아가기
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: 옵션 선택
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: 옵션 변경
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: 적용 혹은 초기화
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: 그룹으로 돌아가기
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: 탐색
    textEng: Navigate
