timeLastSync: 63817557203
entries:
  camp_duration__name:
    id: 2
    text: Длительность стоянки
    textEng: Camp duration
  camp_duration__text:
    id: 2
    text: Время, необходимое для завершения ремонта и медицинских процедур.
    textEng: The time it takes to complete repairs and medical operations.
  camp_supply_limit__name:
    id: 1
    text: Лимит лагерных припасов
    textEng: Camp supply limit
  camp_supply_limit__text:
    id: 1
    text: Максимальное количество припасов, которое можно хранить на базе.
    textEng: The amount of camp supplies that can be stored at the base.
  heat_dissipation__name:
    id: 2
    text: Рассеивание тепла
    textEng: Heat dissipation
  heat_dissipation__text:
    id: 2
    text: Эффективность рассеивания тепла реактора. Чем выше этот показатель, тем чаще можно использовать форсаж.
    textEng: Reactor heat dissipation. Higher values allow the overdrive to be used more frequently.
  mm_normal_speed__name:
    id: 2
    text: Крейсерская скорость
    textEng: Cruise speed
  mm_normal_speed__text:
    id: 2
    text: Скорость передвижения мобильной базы без использования форсажа.
    textEng: The movement speed of the mobile base, without overdrive.
  mm_overdrive_speed__name:
    id: 2
    text: Скорость в форсаже
    textEng: Overdrive speed
  mm_overdrive_speed__text:
    id: 2
    text: Скорость передвижения мобильной базы при использовании форсажа.
    textEng: The movement speed of the mobile base in overdrive.
  pilot_slots__name:
    id: 1
    text: Макс. количество пилотов
    textEng: Pilot limit
  pilot_slots__text:
    id: 1
    text: Сколько пилотов может поддерживать база.
    textEng: Number of pilots the base can support.
  salvage_bonus__name:
    id: 2
    text: Бонус к добыче
    textEng: Salvage bonus
  salvage_bonus__text:
    id: 2
    text: Увеличивает количество добычи, получаемой после каждого задания.
    textEng: An increase to salvage after each mission.
  unit_repair_amount__name:
    id: 1
    text: Ремонтопригодность меха
    textEng: Mech repair capability
  unit_repair_amount__text:
    id: 1
    text: 'Показывает, насколько можно восстановить состояние корпуса меха за одну стоянку. Например: если ремонтопригодность составляет 50%, мех с прочностью 40% будет отремонтирован до 90% за одну стоянку. Этот показатель можно повысить с помощью улучшений базы.'
    textEng: 'How much mech frame integrity can be repaired at one camp stop. For example: if the repair capability is 50%, a mech with 40% integrity will be repaired to 90% after one camp stop. Can be improved with base upgrades.'
  unit_repair_jobs__name:
    id: 1
    text: Ячейки восстановления
    textEng: Recovery slots
  unit_repair_jobs__text:
    id: 1
    text: Количество юнитов и пилотов, которым может быть оказана помощь во время стоянки. Зависит от наличия медицинского отсека и ремонтного оборудования.
    textEng: Number of units and pilots that that can be attended to during a camp stop. Depends on the medical bay and repair equipment.
  unit_slots__name:
    id: 1
    text: Ячейки хранения
    textEng: Storage slots
  unit_slots__text:
    id: 1
    text: Максимальное количество юнитов, хранимых на базе. Определяет, можно ли построить новые юниты.
    textEng: Number of units that can be stored on base. Determines whether new units can be built.
  workshop_jobs__name:
    id: 1
    text: Лимит проекта
    textEng: Project limit
  workshop_jobs__text:
    id: 1
    text: Количество проектов, которое можно создавать в мастерской одновременно.
    textEng: Number of projects the workshop is capable of building simultaneously.
