timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Тест уровней
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Контракты
    textEng: Contracts
  replay__name:
    id: 2
    text: Кампания
    textEng: Campaign
  training__name:
    id: 2
    text: Обучение
    textEng: Training
