timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: Легкий контракт
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: Средний контракт
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: Сложный контракт
    textEng: Challenging contract
