timeLastSync: 63817557565
entries:
  base_briefing_list__s0:
    id: 2
    text: Вернуться к отряду
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: Добавить или убрать
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: Открыть список
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: Очистить ячейку
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: Вернуться к сценарию
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: Перейти к списку
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: Множественный выбор
    textEng: Multi-select
  base_general__header:
    id: 1
    text: Мобильная база
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: Управляйте своими пилотами, юнитами и инвентарем. Расходуйте ресурсы на проекты в мастерской или на улучшения базы. Вернитесь на карту мира, когда будете готовы продолжить кампанию.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: Навигация
    textEng: Navigate
  base_general__s3:
    id: 1
    text: Карта мира
    textEng: World map
  base_general__s4:
    id: 1
    text: Список пилотов
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: Список юнитов
    textEng: Unit list
  base_general__s6:
    id: 1
    text: Инвентарь
    textEng: Inventory
  base_general__s7:
    id: 1
    text: Мастерская
    textEng: Workshop
  base_general__s8:
    id: 1
    text: Улучшения
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: Вернуться к списку
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: Выбрать категорию
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: Открыть категорию
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: Переместить
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: Выбрать предмет
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: Контекстное меню
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: Навигация
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: Вкл/выкл окраску
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: Очистить ячейку
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: Переместить
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: Выбрать значок
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: Выбрать ячейку
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: Открыть ячейку
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: Очистить ячейку
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: Выбрать предмет
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: Установить
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: Вернуться к ячейкам
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: Применить фильтр
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: Навигация по сетке улучшений
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: Прокрутка
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: Переход между улучшениями
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: Перейти к характеристикам
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: Боковая панель в фокусе
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: Вернуться к улучшениям
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: Выбрать характеристики
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: Сменить направление
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: Режим наведения
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: Изменить высоту
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: Пропустить диалог
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: Навигация в фокусе
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: Выбрать юниты
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: Изменить время
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: Таймлайн в фокусе
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: Удалить действие
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: Перетащить действие
    textEng: Drag action
  combat_general__header:
    id: 1
    text: Бой
    textEng: Combat
  combat_general__overview:
    id: 1
    text: Выполните задания, указанные в верхнем правом углу, чтобы одержать победу. Просматривайте предсказанные действия врага, отдавайте приказы вашим юнитам с помощью таймлайна и нажмите кнопку «Выполнить», чтобы посмотреть, как план претворится в жизнь.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: Назад/отмена
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: Подтвердить/выполнить
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: Вкл/выкл замедление времени
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: Навигация
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: Переместить камеру
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: Повернуть камеру
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: Выбрать следующего юнита
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: Выбрать предыдущего юнита
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: Режим наведения
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: Выбрать действие
    textEng: Select action
  combat_general__s9:
    id: 2
    text: Задать шкалу времени
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: Вкл/выкл замедление времени
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: Перейти к управлению временем
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: Выполнить
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: Выполнить
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: Перейти к таймлайну
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: Перейти к действиям
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: Перейти к перемещению
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: Удалить действия
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: Приблизить/отдалить камеру
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: Сменить юнита
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: Вкл/выкл подробности
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: Показать подробности
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: Тест масштаба
    textEng: Zoom test
  credits__s0:
    id: 2
    text: Выйти
    textEng: Exit
  credits__s1:
    id: 2
    text: Прокрутка
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: Пропуск анимаций
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: Подтвердить
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: Назад
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: Выбрать провинцию
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: Переместить карту
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: Выбрать параметр
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: Посмотреть модификаторы
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: Прокрутка
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: Карта мира
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: Передвигайтесь по карте, участвуйте в событиях, нападайте на позиции врага. Сражайтесь за спорные провинции и прогоните захватчиков. Используйте мобильную базу для управления юнитами, пилотами и улучшениями.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: Навигация
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: Выбрать на карте
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: Переместить базу
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: Переместить камеру
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: Повернуть камеру
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: Пауза/возобновить
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: Выбрать параметр
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: Подтвердить
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: Выбрать
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: Переместить
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: Назад
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: Переместить
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: Назад/стоп
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: Вкл/выкл ход времени
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: Выбрать
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: Выбрать параметр
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: Изменить параметр
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: Выбрать шаблон
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: Применить шаблон
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: Перейти к параметрам
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: Выбрать группу
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: Войти в группу
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: Выйти из параметров
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: Выбрать параметр
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: Назначить клавишу
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: Применить или сбросить
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: Вернуться к группам
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: Изменить назначение
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: Назад
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: Выбрать параметр
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: Изменить параметр
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: Применить или сбросить
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: Вернуться к группам
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: Навигация
    textEng: Navigate
