timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Pruebas de nivel
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Contratos
    textEng: Contracts
  replay__name:
    id: 2
    text: Campaña
    textEng: Campaign
  training__name:
    id: 2
    text: Capacitación
    textEng: Training
