timeLastSync: 63817558314
entries:
  base_briefing_list__s0:
    id: 2
    text: Volver al escuadrón
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: Añadir o eliminar
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: Introducir en lista
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: Vaciar ranura
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: Volver al escenario
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: Ir a la lista
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: Multiselección
    textEng: Multi-select
  base_general__header:
    id: 1
    text: Base móvil
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: Gestiona tus pilotos, unidades e inventario. Invierte recursos en proyectos del taller o mejoras de la base. Vuelve al mapa del mundo cuando quieras continuar la campaña.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  base_general__s3:
    id: 1
    text: Mapa del mundo
    textEng: World map
  base_general__s4:
    id: 1
    text: Lista de pilotos
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: Lista de unidades
    textEng: Unit list
  base_general__s6:
    id: 1
    text: Inventario
    textEng: Inventory
  base_general__s7:
    id: 1
    text: Taller
    textEng: Workshop
  base_general__s8:
    id: 1
    text: Mejoras
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: Volver a la lista
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: Seleccionar categoría
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: Abrir categoría
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: Mover
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: Seleccionar objeto
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: Menú contextual
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: Navegar
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: Alternar aspecto
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: Vaciar ranura
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: Mover
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: Seleccionar icono
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: Seleccionar ranura
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: Abrir ranura
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: Vaciar ranura
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: Seleccionar objeto
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: Equipar
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: Volver a las ranuras
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: Aplicar filtros
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: Navegar en cuadrícula de mejora
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: Desplazar
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: Alternar mejoras
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: Ir a las estadísticas
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: Enfocar barra lateral
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: Volver a las mejoras
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: Seleccionar estadísticas
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: Cambiar de dirección
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: Modo de apuntado
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: Altura del apuntado
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: Omitir diálogo
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: Enfocar navegación
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: Seleccionar unidades
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: Cambiar tiempo
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: Enfocar línea temporal
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: Eliminar acción
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: Arrastrar acción
    textEng: Drag action
  combat_general__header:
    id: 1
    text: Combate
    textEng: Combat
  combat_general__overview:
    id: 1
    text: Sigue los objetivos de arriba a la derecha para ganar el combate. Revisa las acciones previstas del enemigo, da órdenes a tus unidades con la línea temporal y ejecuta para poner el plan en acción.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: Atrás/Cancelar
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: Confirmar / Ejecutar
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: Alternar cámara lenta
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: Mover cámara
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: Rotar cámara
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: Seleccionar unidad siguiente
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: Seleccionar unidad anterior
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: Modo de apuntado
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: Seleccionar acción
    textEng: Select action
  combat_general__s9:
    id: 2
    text: Establecer escala de tiempo
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: Alternar cámara lenta
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: Enfocar controles de tiempo
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: Ejecutar
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: Ejecutar
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: Ir a la línea temporal
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: Ir a las acciones
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: Ir al movimiento
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: Eliminar acciones
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: Zoom de cámara
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: Cambiar de unidad
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: Alternar detalles
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: Mostrar detalles
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: Prueba de zoom
    textEng: Zoom test
  credits__s0:
    id: 2
    text: Salir
    textEng: Exit
  credits__s1:
    id: 2
    text: Desplazar
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: Omitir animación
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: Confirmar
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: Volver
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: Seleccionar provincia
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: Mover mapa
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: Seleccionar opción
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: Inspeccionar modificadores
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: Desplazar
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: Mundo
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: Navega por el mapa, participa en eventos, ataca zonas hostiles. Disputa provincias y expulsa a los invasores. Usa la base móvil para gestionar unidades, pilotos y mejoras.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: Seleccionar en el mapa
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: Mover la base
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: Mover cámara
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: Rotar cámara
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: Alternar pausa
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: Seleccionar opción
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: Confirmar
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: Seleccionar
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: Mover
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: Volver
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: Mover
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: Volver / Detenerse
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: Alternar tiempo
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: Seleccionar
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: Seleccionar opción
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: Cambiar opción
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: Seleccionar preajuste
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: Aplicar preajuste
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: Ir a las opciones
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: Seleccionar grupo
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: Acceder a grupo
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: Opciones de salida
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: Seleccionar opción
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: Seleccionar asignación
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: Aplicar o reiniciar
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: Volver a grupos
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: Cambiar asignación
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: Volver
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: Seleccionar opción
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: Cambiar opción
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: Aplicar o reiniciar
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: Volver a grupos
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: Navegar
    textEng: Navigate
