depthBackground: 80
depthForeground: 80
pages:
- depthForeground: 0
  depthBackground: 0
  skippable: true
  cameraInputPermitted: true
  navigationFocus: true
  backgroundUsed: false
  backgroundBlur: false
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.05098039
  center: 
  hint:
    color:
      r: 1
      g: 1
      b: 1
      a: 1
    frameLocation: BottomLeft
    frameGradientMode: Top
    framePositionX: 0
    framePositionY: 0
    frameSizeX: 544
    frameSizeY: 356
    frameBlocksInput: false
    frameBoundary: false
    textLocation: RightTop
    buttonLocation: Bottom
    textWidth: 282
    worldAnchor: 
    arrowCustom: 
    frameHighlight: 
    textLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textLinkController: 
    textInputActions: 
    textInputHintAppendix: 
    effectsOnInput: 
  effectsOverworld: 
  effectsCombat: 
- depthForeground: 0
  depthBackground: 0
  skippable: true
  cameraInputPermitted: true
  navigationFocus: true
  backgroundUsed: false
  backgroundBlur: false
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.05098039
  center: 
  hint:
    color:
      r: 0.4292453
      g: 0.7701125
      b: 1
      a: 1
    frameLocation: BottomLeft
    frameGradientMode: Top
    framePositionX: 14
    framePositionY: 4
    frameSizeX: 422
    frameSizeY: 406
    frameBlocksInput: false
    frameBoundary: false
    textLocation: TopLeft
    buttonLocation: Bottom
    textWidth: 356
    worldAnchor: 
    arrowCustom: 
    frameHighlight: 
    textLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textLinkController: 
    textInputActions: 
    textInputHintAppendix: 
    effectsOnInput: 
  effectsOverworld:
    functions:
    - !CallMethodStatic
      typeName: CIViewBaseBriefingV2
      methodName: OnNavToSquadExternal
      argument: ''
      frameDelay: 1
  effectsCombat: 
- depthForeground: 0
  depthBackground: 0
  skippable: false
  cameraInputPermitted: true
  navigationFocus: true
  backgroundUsed: false
  backgroundBlur: false
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.05098039
  center: 
  hint:
    color:
      r: 0.427451
      g: 0.7686275
      b: 1
      a: 1
    frameLocation: BottomLeft
    frameGradientMode: Top
    framePositionX: 208
    framePositionY: 0
    frameSizeX: 224
    frameSizeY: 424
    frameBlocksInput: false
    frameBoundary: false
    textLocation: TopLeft
    buttonLocation: Bottom
    textWidth: 300
    worldAnchor: 
    arrowCustom:
      offset:
        x: 112
        y: 0
      rotation: 0
    frameHighlight: 
    textLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textLinkController:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textInputActions:
      spriteWrap: true
      actions:
      - global_confirm
    textInputHintAppendix: 
    effectsOnInput:
    - controller: All
      inputDirection: Forward
      functionsOverworld:
      - !CallMethodStatic
        typeName: CIViewBaseBriefingV2
        methodName: OnEditExternal
        argument: ''
        frameDelay: 1
      functionsCombat: 
  effectsOverworld:
    functions:
    - !CallMethodStatic
      typeName: CIViewBaseBriefingV2
      methodName: TrySlotSelection1
      argument: ''
      frameDelay: 1
  effectsCombat: 
- depthForeground: 0
  depthBackground: 0
  skippable: true
  cameraInputPermitted: true
  navigationFocus: true
  backgroundUsed: false
  backgroundBlur: false
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0.05098039
  center:
    textImage: 
    hue: 
    textHeaderLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textContentLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textContentLinkController: 
    textInputActions: 
    textInputHintAppendix: 
  hint: 
  effectsOverworld:
    functions:
    - !CallMethodStatic
      typeName: CIViewBaseLoadout
      methodName: OnSocketSelectedForced
      argument: equipment_right
      frameDelay: 8
  effectsCombat: 
effectsOnEnd:
  effectsOverworld: 
  effectsCombat: 
