depthBackground: 90
depthForeground: 90
pages:
- depthForeground: 0
  depthBackground: 0
  skippable: true
  cameraInputPermitted: true
  navigationFocus: true
  backgroundUsed: false
  backgroundBlur: true
  backgroundColor:
    r: 0
    g: 0
    b: 0
    a: 0
  center:
    textImage: 
    hue: 
    textHeaderLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textContentLink:
      mode: LocUnique
      text: 
      textSector: 
      textKey: 
    textContentLinkController: 
    textInputActions: 
    textInputHintAppendix: 
  hint: 
  effectsOverworld:
    functions:
    - !SelectEntity
      nameInternal: hg_forward_base
      delay: 1
      select: true
      focus: true
  effectsCombat: 
effectsOnEnd:
  effectsOverworld:
    functions:
    - !UnlockCodex
      key: overworld_map_province
  effectsCombat: 
