timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Test di livello
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Contratti
    textEng: Contracts
  replay__name:
    id: 2
    text: Campagna
    textEng: Campaign
  training__name:
    id: 2
    text: Formazione
    textEng: Training
