timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: Contratto facile
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: Contratto medio
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: Contratto difficile
    textEng: Challenging contract
