timeLastSync: 63817554583
entries:
  base_briefing_list__s0:
    id: 2
    text: Torna alla squadra
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: Aggiungi o rimuovi
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: Accedi all'elenco
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: Svuota spazio
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: Torna allo scenario
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: Passa all'elenco
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: Selezione multipla
    textEng: Multi-select
  base_general__header:
    id: 1
    text: Base mobile
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: Gestisci piloti, unità e inventario. Investi risorse in progetti dell'officina o migliorie della base. Torna alla mappa principale di gioco per continuare la campagna.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: Naviga
    textEng: Navigate
  base_general__s3:
    id: 1
    text: Mappa del mondo
    textEng: World map
  base_general__s4:
    id: 1
    text: Elenco piloti
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: Elenco unità
    textEng: Unit list
  base_general__s6:
    id: 1
    text: Inventario
    textEng: Inventory
  base_general__s7:
    id: 1
    text: Officina
    textEng: Workshop
  base_general__s8:
    id: 1
    text: Migliorie
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: Torna all'elenco
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: Seleziona categoria
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: Apri categoria
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: Muoviti
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: Seleziona oggetto
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: Menu di contesto
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: Naviga
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: Usa livrea
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: Svuota spazio
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: Muoviti
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: Seleziona icona
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: Seleziona spazio
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: Apri spazio
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: Svuota spazio
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: Seleziona oggetto
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: Installa
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: Torna agli spazi
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: Applica filtro
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: Navigazione fra migliorie
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: Fai scorrere
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: Salta fra migliorie
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: Passa ai parametri
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: Barra laterale selezionata
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: Torna alle migliorie
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: Seleziona parametri
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: Scambia direzione
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: Modalità mira
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: Altezza mira
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: Salta dialogo
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: Navigazione selezionata
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: Seleziona unità
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: Modifica tempo
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: Linea temporale selezionata
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: Elimina azione
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: Trascina azione
    textEng: Drag action
  combat_general__header:
    id: 1
    text: Combattimento
    textEng: Combat
  combat_general__overview:
    id: 1
    text: Completa gli obiettivi in alto a destra per vincere il combattimento. Analizza le previsioni sulle azioni del nemico, impartisci ordini alle tue unità usando la linea temporale e seleziona Esegui per osservare l'esecuzione del piano.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: Indietro / Annulla
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: Conferma / Esegui
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: Attiva rallentatore
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: Naviga
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: Muovi la telecamera
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: Ruota la telecamera
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: Seleziona unità successiva
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: Seleziona unità precedente
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: Modalità mira
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: Seleziona azione
    textEng: Select action
  combat_general__s9:
    id: 2
    text: Imposta velocità temporale
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: Attiva rallentatore
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: Seleziona i controlli di tempo
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: Esegui
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: Esegui
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: Passa alla linea temporale
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: Passa alle azioni
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: Passa al movimento
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: Rimuovi azioni
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: Zoom
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: Cambia unità
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: Mostra dettagli
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: Mostra dettagli
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: Collaudo zoom
    textEng: Zoom test
  credits__s0:
    id: 2
    text: Esci
    textEng: Exit
  credits__s1:
    id: 2
    text: Fai scorrere
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: Salta animazione
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: Conferma
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: Indietro
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: Seleziona provincia
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: Sposta mappa
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: Seleziona opzione
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: Esamina modificatori
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: Fai scorrere
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: Mappa principale
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: Fatti strada sulla mappa, partecipa agli eventi, attacca siti ostili. Contendi le province al nemico e scaccia le forze d'occupazione. Usa la base mobile per gestire unità, piloti e migliorie.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: Naviga
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: Seleziona sulla mappa
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: Muovi la base
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: Muovi la telecamera
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: Ruota la telecamera
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: Attiva/disattiva pausa
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: Seleziona opzione
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: Conferma
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: Seleziona
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: Muoviti
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: Indietro
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: Muoviti
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: Indietro / Fermati
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: Avvia/ferma tempo
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: Seleziona
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: Seleziona opzione
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: Modifica opzione
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: Seleziona valore predefinito
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: Applica valore predefinito
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: Passa alle opzioni
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: Seleziona gruppo
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: Accedi a gruppo
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: Esci dalle opzioni
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: Seleziona opzione
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: Seleziona associazione
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: Applica o azzera
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: Torna ai gruppi
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: Modifica associazione
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: Indietro
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: Seleziona opzione
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: Modifica opzione
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: Applica o azzera
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: Torna ai gruppi
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: Naviga
    textEng: Navigate
