timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: 簡単な契約
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: 中程度の契約
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: 難しい契約
    textEng: Challenging contract
