hidden: false
parent: armor_bein_m_head
rating: 1
textNameFromPreset: 
textNameFromHardpoint: 
textName: 
textDescFromPreset: 
textDesc: 
hardpoints: 
tags: 
statDistribution: ''
stats: 
visuals:
- part_bein_head
- part_bein_head_uw_boss
attachments: 
activation: 
projectile: 
beam: 
custom: 
functions: 
workshopInfo: 
