hidden: false
parent: armor_bein_m_shoulder
rating: 1
textNameFromPreset: 
textNameFromHardpoint: 
textName: 
textDescFromPreset: 
textDesc: 
hardpoints: 
tags: 
statDistribution: armor
stats:
  barrier:
    value: 0.1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  heat_dissipation:
    value: 0.1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  hp:
    value: 0.1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  mass:
    value: 0.1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  scrap_value:
    value: 0.1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
visuals:
- part_bein_shoulder
- part_bein_shoulder_uw_boss
attachments: 
activation: 
projectile: 
beam: 
custom: 
functions: 
workshopInfo: 
