hidden: false
parent: wpn_main
rating: 1
textNameFromPreset: 
textNameFromHardpoint: 
textName: 
textDescFromPreset: 
textDesc: 
hardpoints: 
tags:
- aihint_stopmovementtofire
- category_wpn_spike
- spec_ballistic
- spec_locking
statDistribution: ''
stats:
  act_count:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_duration:
    value: 1.8
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_heat:
    value: 120
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  mass:
    value: 4
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  scrap_value:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_concussion:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage:
    value: 90
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage_radius:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact:
    value: 80
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact_radius:
    value: 3
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_proj_lifetime:
    value: 0.5
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_max:
    value: 90
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_min:
    value: 30
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle:
    value: 4
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle_moving:
    value: 11
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_speed:
    value: 250
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
visuals:
- wpn_crossbow_pin_01
attachments: 
activation:
  visual:
    local:
      key: fx_muzzle_spike_01
      keyEnemy: 
      scale:
        x: 1
        y: 1
        z: 1
      hueOffset: 
      hueOffsetEnemy: 
    root: 
    localSocketOverride: 
    localHardpointOverride: 
    localTransformOverride: 
  audio:
    onActivationFirst: weapon_tank_cannon
    onActivationMid: weapon_tank_cannon
    onActivationLast: weapon_tank_cannon
    onActivationStart: 
    onActivationEnd: 
  light:
    shared: true
    key: wpn_vhc_cannon
    custom: 
  recoil:
    key: recoil_flat
  timing: 
  hitReaction: 
projectile:
  debugIndexRange: {}
  visual:
    body:
      key: fx_projectile_spear_01_regular
      keyEnemy: 
      scale:
        x: 1
        y: 1
        z: 1
      colorOverride: 
      colorOverrideEnemy: 
    impact:
      key: fx_aoe_hit_01
      keyEnemy: 
      scale:
        x: 2
        y: 2
        z: 2
      hueOffset: 
      hueOffsetEnemy: 
    deactivation:
      key: fx_projectile_pop
      keyEnemy: 
      scale:
        x: 1
        y: 1
        z: 1
      hueOffset: 
      hueOffsetEnemy: 
  audio:
    onImpact: impact_bullet_mech_small
    onDeactivation: 
  damageDelay: 
  distribution: 
  range: 
  fragmentation: 
  fragmentationDelayed: 
  falloff: 
  falloffGlobal: 
  animationFade: 
  ballistics: 
  fuseProximity: 
  spike:
    duration: 1.2
    speed: 50
    reversed: false
    pinDuration: 3
    collisionRadius: 0.5
    collisionLength: 3
  hitResponse:
    unitHitDestruction: true
    propHitDestruction: false
    envHitDestruction: true
    envHitTrigger: true
    envHitAlignmentAmount: 0
  splashDamage: 
  splashImpact: 
  guidanceData: 
  guidanceAudio: 
  statusBuildup: 
  uiTrajectory: 
  uiSpeedAverage: 
  uiEffectivenessMultiplier: 
  uiCoverageWeight: 
  uiOptimumThreshold: 
beam: 
custom: 
functions: 
workshopInfo: 
