hidden: false
parent: wpn_main_heavy
rating: 1
textNameFromPreset: 
textNameFromHardpoint: 
textName: 
textDescFromPreset: 
textDesc: 
hardpoints: 
tags:
- aihint_stopmovementtofire
- category_wpn_cannon
- category_wpn_heavy
- mnf_06
- spec_ballistic
- spec_locking
- type_heavyweight
statDistribution: ''
stats:
  act_count:
    value: 5
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_duration:
    value: 3
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  act_heat:
    value: 228
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  mass:
    value: 25
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  scrap_value:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_concussion:
    value: 3
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage:
    value: 160
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_damage_radius:
    value: 10
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_heat:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact:
    value: 50
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_impact_radius:
    value: 6
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_proj_lifetime:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_proj_ricochet:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_max:
    value: 130
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_range_min:
    value: 55
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle:
    value: 3
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_angle_moving:
    value: 8
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_scatter_radius:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_speed:
    value: 230
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_stagger:
    value: 0
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
  wpn_turnrate_limit:
    value: 1
    targetMode: 0
    targetSocket: ''
    targetHardpoint: ''
visuals: 
attachments:
  h01:
    key: wpn_heavy_minigun_01_top_a
    centered: false
    activated: false
    position:
      x: 0
      y: 0
      z: 0
    rotation:
      x: 0
      y: 0
      z: 0
    scale:
      x: 1
      y: 1
      z: 1
  s02:
    key: wpn_vis_set03_top_04
    centered: false
    activated: false
    position:
      x: 0
      y: -0.657
      z: 1.423
    rotation:
      x: 45
      y: 180
      z: 5.008956E-06
    scale:
      x: 1.3
      y: 1.3
      z: 1.3
  s01:
    key: wpn_melee_sword_03_bottom_b
    centered: false
    activated: false
    position:
      x: 0
      y: 0
      z: -0.1
    rotation:
      x: 315
      y: 180
      z: 0
    scale:
      x: 1.25
      y: 1.25
      z: 1.25
  b01:
    key: wpn_melee_axe_01_top_a_l
    centered: false
    activated: false
    position:
      x: 0
      y: 0.2
      z: 9
    rotation:
      x: 270
      y: 0
      z: 0
    scale:
      x: 1.25
      y: 1.25
      z: 1.25
  f01:
    key: kitbash_parts_01_cylinder_muzzle_04
    centered: false
    activated: true
    position:
      x: 0
      y: 0.2
      z: 8.3
    rotation:
      x: 0
      y: 0
      z: 0
    scale:
      x: 1
      y: 1
      z: 1
  f02:
    key: kitbash_parts_01_cylinder_long_02
    centered: false
    activated: false
    position:
      x: 0
      y: 0.2
      z: 5.1
    rotation:
      x: 0
      y: 0
      z: 0
    scale:
      x: 1.1
      y: 1.1
      z: 1.1
  f03:
    key: kitbash_parts_01_cylinder_medium_02
    centered: false
    activated: false
    position:
      x: 0
      y: 0.526
      z: 0.985
    rotation:
      x: 45
      y: 0
      z: 0
    scale:
      x: 1
      y: 1
      z: 1
activation:
  visual:
    local:
      key: fx_muzzle_tank_cannon
      keyEnemy: 
      scale:
        x: 1
        y: 1
        z: 1
      hueOffset: 
      hueOffsetEnemy: 
    root: 
    localSocketOverride: ''
    localHardpointOverride: ''
    localTransformOverride:
      root: false
      position:
        x: 0
        y: 0.2
        z: 9
      rotation:
        x: 0
        y: 0
        z: 0
  audio:
    onActivationFirst: weapon_tank_cannon
    onActivationMid: weapon_tank_cannon
    onActivationLast: weapon_tank_cannon
    onActivationStart: 
    onActivationEnd: 
  light:
    shared: true
    key: wpn_vhc_cannon
    custom: 
  recoil:
    key: recoil_flat
  timing: 
  hitReaction: 
projectile:
  debugIndexRange: {}
  visual:
    body:
      key: fx_projectile_standard_blue
      keyEnemy: fx_projectile_standard_red
      scale:
        x: 1.2
        y: 1.2
        z: 2
      colorOverride: 
      colorOverrideEnemy: 
    impact:
      key: fx_impact_general_caliber_01
      keyEnemy: 
      scale:
        x: 5
        y: 5
        z: 5
      hueOffset: 
      hueOffsetEnemy: 
    deactivation:
      key: fx_projectile_pop
      keyEnemy: 
      scale:
        x: 1
        y: 1
        z: 1
      hueOffset: 
      hueOffsetEnemy: 
  audio:
    onImpact: impact_bullet_mech_small
    onDeactivation: 
  damageDelay: 
  distribution: 
  range: 
  fragmentation: 
  fragmentationDelayed: 
  falloff:
    animated: true
    referenceStart: 
    referenceMid: 
    referenceEnd: 
    damageFalloff:
      modePostWrap: ClampForever
      modePreWrap: ClampForever
      keys:
      - tv_tg:
          x: 0
          y: 1
          z: 0
          w: 0
        w:
          x: 0
          y: 0
        m: {}
      - tv_tg:
          x: 1
          y: 1
          z: 0
          w: 0
        w:
          x: 0
          y: 0
        m: {}
  falloffGlobal: 
  animationFade: 
  ballistics: 
  fuseProximity:
    distance: 6
    targetExclusive: false
    inertBeforeHit: false
    inertPrimingDelay: 1
    triggerWithoutEntity: false
  spike: 
  hitResponse: 
  splashDamage:
    exponent: 3
    fxDetonation: fx_aoe_explosion_01_medium
    fxDetonationScale: 1
    fxArea: fx_aoe_volume_01
    fxHit: fx_aoe_hit_01
  splashImpact:
    exponent: 2
    triggerOnDamage: false
  guidanceData: 
  guidanceAudio: 
  statusBuildup: 
  uiTrajectory: 
  uiSpeedAverage: 
  uiEffectivenessMultiplier: 
  uiCoverageWeight: 
  uiOptimumThreshold: 
beam: 
custom:
  flags:
  - damage_dispersed
  ints: 
  floats: 
  vectors:
    non_mech_visual_offset:
      x: 0
      y: 0.5
      z: -1.2
  strings: 
functions: 
workshopInfo: 
