icon: s_icon_l32_spec_penetration2
color:
  r: 0.7254902
  g: 0.2862745
  b: 0.2862745
  a: 1
hidden: false
debug: false
showOverlay: false
showNotifications: true
showTutorial: false
restartOnRefresh: false
turnLinked: false
actionLink: 
tags: 
fxAttached: 
fxRepeated: 
durationFull: 
durationUpdate: 
buildupDecayRate: 
buildupThreshold: 
buildupOverflow: 
buildupShieldMultiplier: 
stackable: 
audio: 
effectsOnStart: 
effectsOnUpdate: 
effectsOnEnd: 
statOffsets: 
