comment: 
source: enemy_boss_intercepted
sourceFromEntity: false
priority: false
hold: false
previewDisabled: false
duration: 2
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
