comment: 
source: friendly_homeguard
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 8
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
