comment: 
source: friendly_hq
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 6
audioPitch: 
audioSpeed: 
audioKey: 
order: OrderedForward
functionsOnStart: 
functionsOnExit: 
