comment: 
source: enemy_commander_intercepted
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 6
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
