comment: 
source: friendly_hq
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 3
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
