comment: 
source: friendly_mobilebase
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 5
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
