comment: 
source: friendly_tutorial_major
sourceFromEntity: false
priority: true
hold: false
previewDisabled: false
duration: 0
audioPitch: 
audioSpeed: 
audioKey: 
order: Random
functionsOnStart: 
functionsOnExit: 
