using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using PhantomBrigade;
using PhantomBrigade.Data;

public class PersistentEntity { }
public class OverworldEntity { }
public class OverworldActionEntity { }
public class CombatEntity { }
public class ActionEntity { }
public class EquipmentEntity { }

namespace PhantomBrigade.Game
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.Persistent
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.Overworld
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.Input
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.Combat
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.AI
{
    namespace Components { }
    namespace Systems { }
    namespace BT { }
}

namespace PhantomBrigade.Equipment
{
    namespace Components { }
    namespace Systems { }
}

namespace PhantomBrigade.DebugConsole { }
namespace PhantomBrigade.Linking { }

public enum CombatUIModes
{
    Simulating = 0,
    Unit_Selection = 1,
    Path_Drawing = 2,
    Wait_Drawing = 3,
    Time_Placement = 4,
    Targeting_Units = 5,
    Targeting_Locations = 6,
    AI_Planning = 50,
    Intermission = 60,
    Replay = 90,
    End = 100
}

public class StartEndModifier
{
    public enum Exactness
    {
        SnapToNode,
        Original,
        Interpolate,
        ClosestOnNode,
        NodeConnection
    }
}

public enum UnitStatusSource
{
    Unknown,
    Function,
    Equipment,
    Action,
    PilotAbility,
    Overheat,
    Fatigue,
    Hit,
    Trait
}

public enum UnitFactionFilter
{
    Any,
    Allies,
    Hostiles
}

public class PilotIdentification
{
    public DataStructLocString callsignLoc;
    public string callsignOverride;
        
    public DataStructLocString namePrimaryLoc;
    public DataStructLocString nameSecondaryLoc;
    public string nameOverride;
}

public enum CombatOutcome
{
    Victory = 0,
    Defeat = 1
}

public sealed class MusicReactiveModifier
{
    public enum Mode
    {
        Absolute,
        Relative
    }

    public Mode mode;
    public int value;
    public int numberOfTurns;
    public bool pauseEvaluation;
}

public enum TargetSortMode
{
    None,
    Distance,
    DistanceInv,
    Dot,
    DotInv
}

public enum ScenarioStateRefreshContext
{
    None              = 0,
    OnStepEntry       = 1,
    OnExecutionStart  = 2,
    OnExecutionEnd    = 4,
    OnActionCreated   = 8,
    OnActionDestroyed = 16,
    OnUnitDisabled = 32,
    OnPartDisabled = 64,
    OnLocationContact = 128,
    OnFieldContact = 256,
    OnLevelDestruction = 512
}

public class PlayerDetectionStatus
{
    public enum DetectionState
    {
        NotDetected,
        InProgress,
        Detected
    }
}

public class AgentAIState
{
    //order states in escalating order, so they can be compared
    public enum StateDescription
    {
        Calm = 0,
        Investigating = 1,
        Alerted = 2
    }
}

public enum AIActionType
{
    None,			//Used to block out plans - do not turn plans with this type into actions!
    AttackMain,
    AttackSecondary,
    ReactiveAttackMain,
    ReactiveAttackSecondary,
    Eject,
    Move,
    Wait,
    VentHeat,
    Guard,
    Dash,
    ReactiveGuard
}



// Added to simplify moving 2.0 content over

[Flags]
public enum InputHintMode
{
    None = 0,
    Keyboard = 1,
    Mouse = 2,
    Controller = 4,
    KeyboardMouse = Keyboard | Mouse,
    All = Keyboard | Mouse | Controller
}

public enum InputHintAlignment
{
    Center,
    Left,
    Right
}

public static class CombatUIUtility
{
    public static bool IsFactionFriendly (string faction)
    {
        return !string.Equals (Factions.enemy, faction);
    }
}

// Looks like an IDE suggested autogenerated namespace based on directory hierarchy, too late to change now
namespace Content.Code.CombatOverhaul.Production.Features.AI.Overworld.Commanders
{
    public static class AIIntel
    {
        public const string movementComplete = "movement_complete";
        public const string playerDetected = "player_detected";
        public const string playerLost = "player_lost";
        public const string investigationRequest = "investigation_request";
        public const string undefendedSite = "undefended_site";
    }
}

namespace PhantomBrigade.Overworld.Components
{
    public class CombatSetupStepSlot
    {
        public string spawnGroupKey;
        public bool unitGroupSaved;
        public string unitGroupKey;
        public int unitGroupGrade;
    }
}

namespace PhantomBrigade.Overworld.Systems
{
    public static class OverworldContactCheckKeys
    {
        public const string CheckDroneContact = "CheckDroneContact";
    }
    
    public static class OverworldContactEffectsKeys
    {
        public const string TriggerSelfDestruct = "TriggerSelfDestruct";
        public const string TriggerTargetStun = "TriggerTargetStun";
    }
}

namespace PhantomBrigade.Game
{
    [Serializable]
    public sealed class PilotIdentificationLocOnly
    {
        public DataStructLocString callsignLoc;
        public DataStructLocString namePrimaryLoc;
        public DataStructLocString nameSecondaryLoc;
    }
    
    public class PilotTraitNode
    {
        public string traitKey;
        public string slotKey;
        public int level;
        public PilotTraitSlotType type;
        public bool active;
    }
    
    public enum PilotTraitSlotType
    {
        Starting,
        Acquired,
        Prestige,
        PrestigeEffect,
        Unlockable,
        UnlockableSkipped,
        Conditional,
    }
}

public class UIBasicSprite
{
    public enum Pivot
    {
        TopLeft,
        Top,
        TopRight,
        Left,
        Center,
        Right,
        BottomLeft,
        Bottom,
        BottomRight,
    }
}

public class CIViewTutorialHint
{
    public enum FrameLocation
    {
        TopLeft,
        Top,
        TopRight,
        Left,
        Center,
        Right,
        BottomLeft,
        Bottom,
        BottomRight
    }
    
    public enum FrameGradientMode
    {
        None,
        Top,
        Bottom,
        Left,
        Right
    }
    
    public enum TextLocation
    {
        TopLeft,
        TopRight,
        RightTop,
        RightBottom,
        BottomLeft,
        BottomRight,
        LeftTop,
        LeftBottom
    }
    
    public enum LabelAnchorCorner
    {
        TopLeft,
        TopRight,
        BottomLeft,
        BottomRight
    }
    
    public enum LabelOffsetDirection
    {
        TopLeft,
        TopRight,
        BottomLeft,
        BottomRight
    }
    
    public enum ButtonLocation
    {
        None,
        Top,
        Bottom
    }
}

namespace PhantomBrigade.Data
{
    public enum PointEventType
    {
        Spawn = 0,
        Arrival = 1,
        Expiration = 2,
        Load = 3
    }

    public enum PointChangeType
    {
        Added,
        Changed,
        Completed,
        Removed
    }

    public static class OverworldPointUtility
    {
        public const string memoryPrefixPointKey = "qs_point_comp_key_";
        public const string memoryPrefixPointTag = "qs_point_comp_tag_";
    }

    public static class DataHelperStats
    {
        public static float unitSizeAverageHalf = 2.5f;
    }
    
    public static class ScenarioFunctionKeys
    {
        public const string OnEndTutorialIntro = "OnEndTutorialIntro";
        public const string OnEndCapital = "OnEndCapital";
        public const string OnEndMountainBase = "OnEndMountainBase";
    }

    public static class PilotUtility
    {
        public const int dataVersion = 3;

        public static List<PilotEventType> pilotEventTypesList = new List<PilotEventType> ((PilotEventType[])Enum.GetValues (typeof (PilotEventType)));

        public static HashSet<PilotEventType> pilotEventTypesWithEntities = new HashSet<PilotEventType>
        {
            PilotEventType.CombatPilotKnockoutEnemy,
            PilotEventType.CombatPilotKnockoutAlly,

            PilotEventType.CombatUnitTakedownEnemy,
            PilotEventType.CombatUnitTakedownAlly,

            PilotEventType.CombatUnitDamageIncoming,

            PilotEventType.CombatUnitCrashLost,
            PilotEventType.CombatUnitCrashWon,
            PilotEventType.CombatUnitCrashWonShielded
        };
    }
}

namespace PhantomBrigade.AI
{
    public static class CombatAITargetingUtils
    {
        public enum StatType
        {
            //stats that are populated once
            CurrentHP,
            MaxHP,
            CurrentHPNormalized,
            MinCriticalHPNormalized,
            Speed,

            TargetedCount,

            //stats that are updated per-entity doing the targeting
            Random,
            Distance,
            PrimaryAttackFalloff,
            SecondaryAttackFalloff,
            AnyAttackFalloff,
            LineOfSight,

            Count
        }
    }
}

namespace QFSW.QC
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
    public sealed class CommandPrefixAttribute : Attribute
    {
        public readonly string Prefix;

        public CommandPrefixAttribute([CallerMemberName] string prefixName = "")
        {
            Prefix = prefixName;
        }
    }
    
    [AttributeUsage(AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = true, Inherited = false)]
    public sealed class CommandAttribute : Attribute
    {
        public readonly string Alias;
        public readonly string Description;

        public CommandAttribute ([CallerMemberName] string aliasOverride = "", string description = "")
        {
            Alias = aliasOverride;
            Description = description;
        } 
    }
}

namespace PhantomBrigade
{
    public enum GameEventType
    {
        CampaignStart,
        CampaignExit,
        
        OverworldContextEnabled,
        OverworldContextDisabled,
        OverworldTimeSkipStart,
        OverworldTimeSkipEnd,
        OverworldTimeSkipEndCamp,
        OverworldTimeSkipEndResupply,
        OverworldTimeMinute,
        OverworldTimeHour,
        OverworldTimeDay,
        
        OverworldProvinceChange,
        OverworldQuestStepEntry,
        OverworldQuestMemory,
        OverworldResetReached,
        
        OverworldPointSpawn,
        OverworldPointInteractionStart,
        OverworldPointInteractionEnd,
        OverworldPointDestruction,
        OverworldPointExpiration,
        OverworldPointCombatEndEarly,
        OverworldPointCombatEndLate,
        OverworldPointCombatPostDebriefing,
        OverworldPointCombatVictory,
        OverworldPointCombatDefeat,
        
        BaseContextEnabled,
        BaseContextDisabled,
        
        CombatContextEnabled,
        CombatContextDisabled
    }
    
    public enum GameEventObject
    {
        ViewEntry, // UI screen - CIView
        ViewExit, // UI screen - CIView
        UnitStatsRefresh, // Unit - PersistentEntity
        BasePartInstalled, // Blueprint - DataContainerBasePart
        PilotAdded, // Pilot - PersistentEntity
        UnitBuilt, // Unit - PersistentEntity
        PartBuilt, // Part - EquipmentEntity
        SubsystemBuilt, // Subsystem - EquipmentEntity
        WorkshopBuildComplete // Processed project - DataBlockWorkshopProjectProcessed
    }
    
    public static class IDUtility
    {
        public const int invalidID = -99;
    }
}

namespace Pathfinding
{
    public class StartEndModifier
    {
		public enum Exactness 
        {
			SnapToNode,
			Original,
			Interpolate,
			ClosestOnNode,
			NodeConnection,
		}
    }
}

public interface IComponent
{
}

namespace Entitas.VisualDebugging.Unity
{
    [AttributeUsage(AttributeTargets.Class)]
    public class DontDrawComponentAttribute : Attribute
    {
    
    }
}

namespace Entitas.CodeGeneration.Attributes
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Property | AttributeTargets.Field)]
    public class EntityIndexAttribute : Attribute
    {

    }
    
    public class ContextAttribute : Attribute
    {
        public readonly string contextName;

        public ContextAttribute (string contextName) => this.contextName = contextName;
    }
}

public sealed class GameAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public GameAttribute() : base("Game") { }
}

public sealed class AIAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public AIAttribute() : base("AI") { }
}

public sealed class ActionAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public ActionAttribute () : base("Action") { }
}

public sealed class OverworldActionAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public OverworldActionAttribute() : base("OverworldAction") { }
}


public sealed class CombatAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public CombatAttribute () : base("Combat") { }
}

public sealed class OverworldAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public OverworldAttribute () : base("Overworld") { }
}

public sealed class PersistentAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public PersistentAttribute () : base("Persistent") { }
}

public sealed class EquipmentAttribute : Entitas.CodeGeneration.Attributes.ContextAttribute 
{
    public EquipmentAttribute() : base("Equipment") { }
}