hidden: true
parents: 
core: 
tags:
- difficulty_medium
- difficulty_easy
textList: 
escalation: 
levelOffset: 
checksGlobal: 
checksBase: 
scenarioFilter: 
scenarioChanges: 
squads:
- comment:
    comment: 3 units, 0-1 level boost
  scenarioTagsRequired: 
  scenarioTagsBlocked: 
  slots:
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g3_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 1
    presetFilter:
      tagsUsed: false
      keys:
      - vhc_mech_w3_3f_heavy_01
      - vhc_mech_w3_3f_heavy_02
      tags: 
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g2_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 1
    presetFilter:
      tagsUsed: false
      keys:
      - vhc_mech_w3_3f_heavy_02
      - vhc_mech_w3_3f_heavy_03
      tags: 
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g1_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 1
    presetFilter:
      tagsUsed: false
      keys:
      - vhc_mech_w3_3f_heavy_03
      - vhc_mech_w3_3f_heavy_04
      tags: 
squadFilter: 
rewardPool: 
effectsOnCompletion: 
