hidden: true
parents: 
core: 
tags:
- difficulty_hard
- difficulty_easy
- difficulty_medium
textList: 
escalation: 
levelOffset: 
checksGlobal: 
checksBase: 
scenarioFilter: 
scenarioChanges: 
squads:
- comment:
    comment: 3 units, +1 level
  scenarioTagsRequired: 
  scenarioTagsBlocked: 
  slots:
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g3_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_heavy: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g2_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_medium: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g1_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_light: true
- comment:
    comment: 3 units, +1 level
  scenarioTagsRequired: 
  scenarioTagsBlocked: 
  slots:
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g3_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_heavy: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g2_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_heavy: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g1_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_medium: true
- comment:
    comment: 3 units, +1 level
  scenarioTagsRequired: 
  scenarioTagsBlocked: 
  slots:
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g3_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_medium: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g2_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_light: true
  - qualityTable: unitgroup_q2_uncommon
    livery: hg_main_g1_green_arm
    levelOffsetMin: 0
    levelOffsetMax: 2
    presetFilter:
      tagsUsed: true
      keys: 
      tags:
        role_3f_squads: true
        type_mech: true
        weight_light: true
squadFilter: 
rewardPool: 
effectsOnCompletion: 
