color:
  r: 1
  g: 1
  b: 1
  a: 1
hidden: false
icon: s_icon_l32_part_weapon_ranged
text:
  mode: LocReused
  text: 
  textSector: overworld_rewards
  textKey: part_weapon_sr__name
tags:
- part_general_lq
- part_weapon_lq
resources: 
projects: 
parts:
- factionFilter: true
  qualityTableKey: reward_generic_q2
  levelRange: 
  countMin: 1
  countMax: 1
  countRandom: false
  tagsUsed: true
  keys: 
  tags:
    item_part: true
    part_melee: false
    range_short: true
subsystems: 
