color:
  r: 0.7660131
  g: 0.8862745
  b: 0.7058824
  a: 1
hidden: false
icon: s_icon_m_unit_mech4
text:
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
tags:
- subsystem
- subsystem_general
resources: 
projects: 
parts: 
subsystems:
- ratingRange: 
  countMin: 1
  countMax: 2
  countRandom: true
  tagsUsed: true
  keys: 
  tags:
    internal_aux: true
    rating_1: false
