timeLastSync: 0
localized: false
exportMode: None
name: 
description: 
splits: []
tags: 
groups: 
entries:
  dlc1_m01_s00_body:
    noteDev: 
    temp: true
    text: Decoding remote transmission...
  dlc1_m01_s01_body:
    noteDev: 
    temp: true
    text: Received request for remote assistance...
  dlc1_m01_s01_m_00:
    noteDev: 
    temp: true
    text: Signal source
  dlc1_m01_s02_body:
    noteDev: 
    temp: true
    text: Signal triangulated. Ready to connect.
  dlc1_m01_s02_m_loc_name:
    noteDev: 
    temp: true
    text: Shoreline-7
  dlc1_m01_s02_m_loc_subtitle:
    noteDev: 
    temp: true
    text: Kaskad Navy Logistics Hub
