timeLastSync: 0
localized: true
exportMode: LinePerKeySimple
name: 
description: 
splits: []
tags: 
groups: 
entries:
  dev_areas_listed__name:
    noteDev: 
    temp: false
    text: Area testing
  gen_contracts__name:
    noteDev: 
    temp: false
    text: Contracts
  replay__name:
    noteDev: 
    temp: false
    text: Campaign
  training__name:
    noteDev: 
    temp: false
    text: Training
