hidden: false
format: 0.##
debugAmount: 10000
priority: 0
colorOverrideBar: 
colorOverrideRewards: 
showCounter: true
showCounterNegative: true
maxOnResupply: false
icon: s_icon_res_supplies2
baseStatLimit: 
basePartForResupply: 
constantLimit:
  f: 10000
offsetOnResupply: 
statLinks:
  scrap_value:
    multiplier: 1
