timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Teste de nível
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Contratos
    textEng: Contracts
  replay__name:
    id: 2
    text: Campanha
    textEng: Campaign
  training__name:
    id: 2
    text: Treinamento
    textEng: Training
