timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: Contrato fácil
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: Contrato médio
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: Contrato difícil
    textEng: Challenging contract
