timeLastSync: 63822798852
entries:
  base_briefing_list__s0:
    id: 2
    text: Retornar ao esquadrão
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: Adicionar ou remover
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: Entrar na lista
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: Liberar espaço
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: Retornar ao cenário
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: Ir para a lista
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: Multisseletivo
    textEng: Multi-select
  base_general__header:
    id: 1
    text: Base móvel
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: Gerencie seus mekanautas, suas unidades e seu inventário. Invista recursos em projetos da oficina ou em melhorias da base. Retorne ao mapa do mundo quando quiser continuar sua campanha.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  base_general__s3:
    id: 1
    text: Mapa do mundo
    textEng: World map
  base_general__s4:
    id: 1
    text: Lista de mekanautas
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: Lista de unidades
    textEng: Unit list
  base_general__s6:
    id: 1
    text: Inventário
    textEng: Inventory
  base_general__s7:
    id: 1
    text: Oficina
    textEng: Workshop
  base_general__s8:
    id: 1
    text: Melhorias
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: Retornar à lista
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: Selecionar categoria
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: Abrir categoria
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: Mover
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: Selecionar item
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: Menu contextual
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: Navegar
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: Trocar visuais
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: Liberar espaço
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: Mover
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: Selecionar ícone
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: Selecionar espaço
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: Abrir espaço
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: Liberar espaço
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: Selecionar item
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: Equipar
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: Retornar aos espaços
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: Aplicar filtro
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: Navegando grade de melhorias
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: Navegar
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: Saltar entre melhorias
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: Passar para atributos
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: Barra lateral em foco
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: Retornar às melhorias
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: Selecionar atributos
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: Trocar direção
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: Modo alvo
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: Altura de ataque
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: Pular diálogo
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: Navegação em foco
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: Selecionar unidades
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: Alterar tempo
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: Linha temporal em foco
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: Remover ação
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: Arrastar ação
    textEng: Drag action
  combat_general__header:
    id: 1
    text: Combate
    textEng: Combat
  combat_general__overview:
    id: 1
    text: Siga os objetivos no canto superior direito para vencer o combate. Analise as ações inimigas previstas, dê ordens às suas unidades pela linha temporal e execute para ver o plano em ação.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: Voltar / Cancelar
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: Confirmar / Executar
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: Ativar/desativar câmera lenta
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: Mover câmera
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: Girar câmera
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: Selecionar próxima unidade
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: Selecionar unidade anterior
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: Modo de aquisição de alvos
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: Selecionar ação
    textEng: Select action
  combat_general__s9:
    id: 2
    text: Definir escala de tempo
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: Ativar/desativar câmera lenta
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: Controles do tempo de foco
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: Executar
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: Executar
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: Passar para linha temporal
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: Passar para ações
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: Passar para movimentação
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: Remover ações
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: Zoom da câmera
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: Trocar unidade
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: Exibir/ocultar detalhes
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: Exibir detalhes
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: Testar zoom
    textEng: Zoom test
  credits__s0:
    id: 2
    text: Sair
    textEng: Exit
  credits__s1:
    id: 2
    text: Navegar
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: Pular animação
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: Confirmar
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: Retornar
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: Selecionar província
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: Mover mapa
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: Selecionar opção
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: Inspecionar modificadores
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: Navegar
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: Mapa do mundo
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: Movimente-se pelo mapa, participe de eventos, ataque áreas inimigas. Dispute províncias e expulse as forças invasoras. Use a base móvel para gerenciar unidades, mekanautas e melhorias.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: Navegar
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: Selecione no mapa
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: Mover a base
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: Mover câmera
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: Girar câmera
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: Pausar/continuar
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: Selecionar opção
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: Confirmar
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: Selecionar
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: Mover
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: Retornar
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: Mover
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: Retornar / Parar
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: Alternar tempo
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: Selecionar
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: Selecionar opção
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: Alterar opção
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: Selecionar predefinição
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: Aplicar predefinição
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: Ir para opções
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: Selecionar grupo
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: Entrar no grupo
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: Fechar opções
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: Selecionar opção
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: Selecionar comando
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: Aplicar ou reverter
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: Retornar aos grupos
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: Alterar comando
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: Retornar
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: Selecionar opção
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: Alterar opção
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: Aplicar ou reverter
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: Retornar aos grupos
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: Navegar
    textEng: Navigate
