timeLastSync: 63817551232
entries:
  camp_duration__name:
    id: 2
    text: 扎营时长
    textEng: Camp duration
  camp_duration__text:
    id: 2
    text: 完成维修和医疗处理所需的时间。
    textEng: The time it takes to complete repairs and medical operations.
  camp_supply_limit__name:
    id: 1
    text: 营地补给上限
    textEng: Camp supply limit
  camp_supply_limit__text:
    id: 1
    text: 基地可以存放的营地补给总量。
    textEng: The amount of camp supplies that can be stored at the base.
  heat_dissipation__name:
    id: 2
    text: 散热量
    textEng: Heat dissipation
  heat_dissipation__text:
    id: 2
    text: 反应堆的散热能力。数值越高，超速模式的可使用频率就越高。
    textEng: Reactor heat dissipation. Higher values allow the overdrive to be used more frequently.
  mm_normal_speed__name:
    id: 2
    text: 巡航速度
    textEng: Cruise speed
  mm_normal_speed__text:
    id: 2
    text: 移动基地在非超速状态下的移动速度。
    textEng: The movement speed of the mobile base, without overdrive.
  mm_overdrive_speed__name:
    id: 2
    text: 超速速度
    textEng: Overdrive speed
  mm_overdrive_speed__text:
    id: 2
    text: 移动基地在超速状态下的移动速度。
    textEng: The movement speed of the mobile base in overdrive.
  pilot_slots__name:
    id: 1
    text: 驾驶员限制
    textEng: Pilot limit
  pilot_slots__text:
    id: 1
    text: 基地可以支持的驾驶员人数。
    textEng: Number of pilots the base can support.
  salvage_bonus__name:
    id: 2
    text: 回收加成
    textEng: Salvage bonus
  salvage_bonus__text:
    id: 2
    text: 每次任务结束后获得的回收资源增加。
    textEng: An increase to salvage after each mission.
  unit_repair_amount__name:
    id: 1
    text: 机甲维修能力
    textEng: Mech repair capability
  unit_repair_amount__text:
    id: 1
    text: 每次扎营停驻期间可以修复的机甲支架完整性。例如：若修复能力为50%，一台机甲完整性为40%的机甲在一次扎营停驻后将修复至90%。可通过基地升级提升。
    textEng: 'How much mech frame integrity can be repaired at one camp stop. For example: if the repair capability is 50%, a mech with 40% integrity will be repaired to 90% after one camp stop. Can be improved with base upgrades.'
  unit_repair_jobs__name:
    id: 1
    text: 恢复槽位
    textEng: Recovery slots
  unit_repair_jobs__text:
    id: 1
    text: 每次扎营停驻期间可修复或治疗的单位与驾驶员数量。具体数量取决于医疗舱和维修设备。
    textEng: Number of units and pilots that that can be attended to during a camp stop. Depends on the medical bay and repair equipment.
  unit_slots__name:
    id: 1
    text: 存储槽位
    textEng: Storage slots
  unit_slots__text:
    id: 1
    text: 可存放在基地的单位数量。决定你是否可以建造新的单位。
    textEng: Number of units that can be stored on base. Determines whether new units can be built.
  workshop_jobs__name:
    id: 1
    text: 项目上限
    textEng: Project limit
  workshop_jobs__text:
    id: 1
    text: 车间能够同时建造的项目数量。
    textEng: Number of projects the workshop is capable of building simultaneously.
