timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: 等级测试
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: 合约
    textEng: Contracts
  replay__name:
    id: 2
    text: 战役
    textEng: Campaign
  training__name:
    id: 2
    text: 训练
    textEng: Training
