timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: 简单合约
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: 中等合约
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: 高难度合约
    textEng: Challenging contract
