timeLastSync: 63817551589
entries:
  base_briefing_list__s0:
    id: 2
    text: 返回小队
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: 添加或移除
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: 进入列表
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: 清空槽位
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: 返回场景
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: 跳转至列表
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: 多选
    textEng: Multi-select
  base_general__header:
    id: 1
    text: 移动基地
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: 管理你的驾驶员、单位和库存。将资源投入车间项目或基地升级。当你准备好继续你的事业时，请返回主世界。
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: 导航
    textEng: Navigate
  base_general__s3:
    id: 1
    text: 世界地图
    textEng: World map
  base_general__s4:
    id: 1
    text: 驾驶员列表
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: 单位列表
    textEng: Unit list
  base_general__s6:
    id: 1
    text: 库存
    textEng: Inventory
  base_general__s7:
    id: 1
    text: 车间
    textEng: Workshop
  base_general__s8:
    id: 1
    text: 升级
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: 返回列表
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: 选择类别
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: 打开类别
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: 移动
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: 选择物品
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: 上下文菜单
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: 导航
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: 切换涂装
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: 清空槽位
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: 移动
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: 选择图标
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: 选择槽位
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: 打开槽位
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: 清空槽位
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: 选择物品
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: 装备
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: 返回槽位
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: 应用筛选
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: 升级网格导航
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: 滚动
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: 切换升级项
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: 跳转到属性
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: 选中侧边栏
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: 返回升级
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: 选择属性
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: 切换方向
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: 瞄准模式
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: 微调高度
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: 跳过对话
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: 选中导航栏
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: 选择单位
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: 更改时间
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: 选中时间轴
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: 删除动作
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: 拖拽动作
    textEng: Drag action
  combat_general__header:
    id: 1
    text: 战斗
    textEng: Combat
  combat_general__overview:
    id: 1
    text: 按照右上角的目标来赢得战斗。回顾已预测的敌人行动，使用时间线向你的单位下达命令并执行计划。
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: 返回/取消
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: 确认/执行
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: 切换慢动作
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: 导航
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: 移动镜头
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: 旋转镜头
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: 选择下一个单位
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: 选择上一个单位
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: 瞄准模式
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: 选择动作
    textEng: Select action
  combat_general__s9:
    id: 2
    text: 设置时间流速
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: 切换慢动作
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: 选中时间控件
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: 执行
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: 执行
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: 跳转到时间轴
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: 跳转到动作
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: 跳转到移动
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: 移除动作
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: 缩放镜头
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: 切换单位
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: 切换详情
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: 显示详情
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: 测试缩放
    textEng: Zoom test
  credits__s0:
    id: 2
    text: 退出
    textEng: Exit
  credits__s1:
    id: 2
    text: 滚动
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: 跳过动画
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: 确认
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: 返回
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: 选择省份
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: 移动地图
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: 选择选项
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: 查看修改器
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: 滚动
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: 主世界
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: 在地图上移动，参与事件，攻击敌方阵地。争夺省份并赶走侵略军。使用移动基地来管理单位、驾驶员和升级。
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: 导航
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: 在地图上选择
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: 移动基地
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: 移动镜头
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: 旋转镜头
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: 切换暂停
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: 选择选项
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: 确认
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: 选择
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: 移动
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: 返回
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: 移动
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: 返回/停止
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: 切换时间
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: 选择
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: 选择选项
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: 更改选项
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: 选择预设
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: 应用预设
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: 跳转到选项
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: 选择分组
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: 进入分组
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: 退出选项
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: 选择选项
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: 选择绑定
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: 应用或重置
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: 返回分组
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: 更改绑定
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: 返回
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: 选择选项
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: 更改选项
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: 应用或重置
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: 返回分组
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: 导航
    textEng: Navigate
