hidden: true
steps:
- color:
    r: 0
    g: 1
    b: 0.6666667
    a: 1
  slide: 
  background: 
  map: 
  textBody:
    mode: LocUnique
    text: 
    textSector: 
    textKey: 
- color:
    r: 0
    g: 1
    b: 0.3333333
    a: 1
  slide: 
  background: 
  map:
    image: 
    x: -224
    y: 0
    scale: 1
    markers:
    - key: 
      time: 1
      x: -224
      y: 6.4
      color:
        v:
          r: 0.6
          g: 1
          b: 0.7333333
          a: 1
      size: 
      rotation: 
      duration: 
      style: base_s_r
      icon: deco_cross_32px
      text:
        mode: LocUnique
        text: 
        textSector: 
        textKey: 
  textBody:
    mode: LocUnique
    text: 
    textSector: 
    textKey: 
- color:
    r: 1
    g: 0
    b: 0
    a: 1
  slide: 
  background: 
  map:
    image: 
    x: -512
    y: 0
    scale: 2
    markers:
    - key: 
      time: 0.5
      x: -225.5
      y: 6.4
      color:
        v:
          r: 0.6
          g: 1
          b: 0.7333333
          a: 1
      size: 
      rotation: 
      duration: 
      style: 
      icon: deco_cross_32px
      text: 
    - key: 
      time: 4
      x: -244
      y: -20
      color:
        v:
          r: 1
          g: 0.5424528
          b: 0.5424528
          a: 1
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_mnf_organic
      text: 
    - key: loc_name
      time: 4.5
      x: -244
      y: -20
      color: 
      size: 
      rotation: 
      duration: 
      style: base_l_c
      icon: s_icon_l48_context2
      text:
        mode: LocUnique
        text: 
        textSector: 
        textKey: 
    - key: loc_subtitle
      time: 5
      x: -244
      y: -36
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 1
      size: 
      rotation: 
      duration: 
      style: base_m_c
      icon: 
      text:
        mode: LocUnique
        text: 
        textSector: 
        textKey: 
    - key: 
      time: 1
      x: -225.5
      y: 6.4
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 1
      size:
        x: 256
        y: 256
      rotation:
        f: -45
      duration:
        f: 1
      style: grid1
      icon: 
      text: 
    - key: 
      time: 2
      x: -200
      y: 32
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 0.7607843
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_star1
      text: 
    - key: 
      time: 2.5
      x: -190
      y: 16
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 1
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_star2
      text: 
    - key: 
      time: 2.75
      x: -200
      y: 0
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 1
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_star3
      text: 
    - key: 
      time: 3
      x: -210
      y: -16
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 0.7450981
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_star1
      text: 
    - key: 
      time: 3.5
      x: -289.5
      y: 6.4
      color:
        v:
          r: 1
          g: 0.6
          b: 0.6
          a: 0.5450981
      size: 
      rotation: 
      duration: 
      style: 
      icon: s_icon_l32_star2
      text: 
    - key: 
      time: 4
      x: -244
      y: -36
      color:
        v:
          r: 0.6981132
          g: 0.5565147
          b: 0.5565147
          a: 1
      size:
        x: 512
        y: 256
      rotation: 
      duration: 
      style: grid1
      icon: 
      text: 
  textBody:
    mode: LocUnique
    text: 
    textSector: 
    textKey: 
