timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Tests de niveau
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Contrats
    textEng: Contracts
  replay__name:
    id: 2
    text: Campagne
    textEng: Campaign
  training__name:
    id: 2
    text: Formation
    textEng: Training
