timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: Contrat simple
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: Contrat moyen
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: Contrat difficile
    textEng: Challenging contract
