timeLastSync: 63817553098
entries:
  base_briefing_list__s0:
    id: 2
    text: Retour à l'escouade
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: Ajouter ou retirer
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: Ouvrir la liste
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: Vider l'emplacement
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: Retour au scénario
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: Accéder à la liste
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: Sélection multiple
    textEng: Multi-select
  base_general__header:
    id: 1
    text: Base mobile
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: Gérez vos pilotes, vos unités et votre inventaire. Investissez des ressources dans des projets à l'atelier ou pour améliorer la base. Revenez à la carte du monde lorsque vous êtes prêt à poursuivre votre campagne.
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: Aller
    textEng: Navigate
  base_general__s3:
    id: 1
    text: Carte du monde
    textEng: World map
  base_general__s4:
    id: 1
    text: Liste des pilotes
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: Liste des unités
    textEng: Unit list
  base_general__s6:
    id: 1
    text: Inventaire
    textEng: Inventory
  base_general__s7:
    id: 1
    text: Atelier
    textEng: Workshop
  base_general__s8:
    id: 1
    text: Améliorations
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: Retour à la liste
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: Sélectionner la catégorie
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: Ouvrir la catégorie
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: Déplacer
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: Sélectionner un objet
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: Menu contextuel
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: Aller
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: Activer/désactiver l'apparence
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: Vider l'emplacement
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: Déplacer
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: Sélectionner l'icône
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: Sélectionner l'emplacement
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: Ouvrir l'emplacement
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: Vider l'emplacement
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: Sélectionner un objet
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: Équiper
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: Retour aux emplacements
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: Appliquer le filtre
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: Parcourir la grille d'améliorations
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: Faire défiler
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: Parcourir les améliorations
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: Accéder aux caractéristiques
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: Barre latérale sélectionnée
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: Retour aux améliorations
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: Sélectionner les caractéristiques
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: Changer de direction
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: Mode de ciblage
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: Hauteur d'attaque
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: Passer les dialogues
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: Navigation sélectionnée
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: Sélectionner des unités
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: Modifier le temps
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: Frise temporelle sélectionnée
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: Supprimer l'action
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: Faire glisser l'action
    textEng: Drag action
  combat_general__header:
    id: 1
    text: En combat
    textEng: Combat
  combat_general__overview:
    id: 1
    text: Suivez les objectifs dans le coin supérieur droit pour remporter le combat. Passez en revue les actions ennemies prévues, donnez des ordres à vos unités en utilisant la frise temporelle, et exécutez votre plan.
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: Retour/annuler
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: Confirmer/exécuter
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: Activer/désactiver le ralenti
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: Aller
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: Déplacer la caméra
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: Tourner la caméra
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: Sélectionner l'unité suivante
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: Sélectionner l'unité précédente
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: Mode de visée
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: Sélectionner l'action
    textEng: Select action
  combat_general__s9:
    id: 2
    text: Régler l'échelle de temps
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: Activer/désactiver le ralenti
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: Sélectionner les commandes temporelles
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: Exécuter
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: Exécuter
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: Accéder à la frise temporelle
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: Accéder aux actions
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: Accéder aux déplacements
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: Supprimer les actions
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: Zoom de la caméra
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: Changer d'unité
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: Afficher/masquer les détails
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: Afficher les détails
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: Test du zoom
    textEng: Zoom test
  credits__s0:
    id: 2
    text: Quitter
    textEng: Exit
  credits__s1:
    id: 2
    text: Faire défiler
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: Passer l'animation
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: Confirmer
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: Retour
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: Sélectionner la province
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: Parcourir la carte
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: Sélectionner l'option
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: Inspecter les modificateurs
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: Faire défiler
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: Carte du monde
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: Naviguez sur la carte, participez aux événements, attaquez les positions ennemies. Contestez les provinces et chassez les forces d'invasion. Utilisez la base mobile pour gérer les unités, les pilotes et les améliorations.
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: Aller
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: Sélectionner sur la carte
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: Déplacer la base
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: Déplacer la caméra
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: Tourner la caméra
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: Mettre en pause/reprendre
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: Sélectionner l'option
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: Confirmer
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: Sélectionner
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: Déplacer
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: Retour
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: Déplacer
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: Retour/arrêt
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: Arrêter/faire défiler le temps
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: Sélectionner
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: Sélectionner l'option
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: Modifier l'option
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: Sélectionner le préréglage
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: Appliquer le préréglage
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: Accéder aux options
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: Sélectionner le groupe
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: Accès au groupe
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: Quitter les options
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: Sélectionner l'option
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: Sélectionner l'association
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: Appliquer ou réinitialiser
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: Retour aux groupes
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: Modifier l'association
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: Retour
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: Sélectionner l'option
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: Modifier l'option
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: Appliquer ou réinitialiser
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: Retour aux groupes
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: Aller
    textEng: Navigate
