noteLoc: 
hue: 0.4444444
priority: 7
parent: base
listed: true
unlockable: true
unlockOnQuickStart: true
sections:
- !CodexSectionImage
  image: briefing_contracts
  group: codex
- !CodexSectionTextSimple
  color:
    r: 1
    g: 1
    b: 1
    a: 1
- !CodexSectionTextExternalSimple
  color:
    r: 1
    g: 1
    b: 1
    a: 1
  textSector: ui_tutorials
  textKey: base_standalone_ops__p01_hint
- !CodexSectionTextExternalSimple
  color:
    r: 1
    g: 0.8529412
    b: 0.6470588
    a: 1
  textSector: ui_tutorials
  textKey: base_standalone_ops__p02_text
