hidden: false
instant: true
priority: 8
mode: String
group: accessibility
header: 
valueDefault: s2_bg1
valueMin: 
valueMax: 
valueSuffix: 
valueFormat: 
valueVisualMultiplier: 1
levelsUsedForInput: true
levelsUsedForUI: true
levelsLocalized: false
entKey: 
levels:
  s2_bg0:
    textCustom: 2 I
    valueRaw: s2_bg0
  s2_bg1:
    textCustom: 2 I[aa]I
    valueRaw: s2_bg1
  s2_bg2:
    textCustom: 2 I[aa]I[66]I
    valueRaw: s2_bg2
  s4_bg1:
    textCustom: 4 I[aa]I
    valueRaw: s4_bg1
  s4_bg2:
    textCustom: 4 I[aa]I[66]I
    valueRaw: s4_bg2
  s8_bg1:
    textCustom: 8 I[aa]I
    valueRaw: s8_bg1
  s8_bg2:
    textCustom: 8 I[aa]I[66]I
    valueRaw: s8_bg2
upgrades: 
