hidden: false
instant: true
priority: 8
mode: String
group: accessibility
header: 
valueDefault: 5
valueMin: 
valueMax: 
valueSuffix: 
valueFormat: 
valueVisualMultiplier: 1
levelsUsedForInput: false
levelsUsedForUI: true
levelsLocalized: false
entKey: 
levels:
  010:
    textCustom: 1
    valueRaw: 1
  030:
    textCustom: 3
    valueRaw: 3
  050:
    textCustom: 5
    valueRaw: 5
  100:
    textCustom: 10
    valueRaw: 10
  200:
    textCustom: 20
    valueRaw: 20
upgrades: 
