hidden: false
instant: true
priority: 0
mode: Bool
group: controls_mkb
header: 
valueDefault: true
valueMin: 
valueMax: 
valueSuffix: 
valueFormat: 
valueVisualMultiplier: 1
levelsUsedForInput: true
levelsUsedForUI: true
levelsLocalized: true
entKey: 
levels: 
upgrades: 
