hidden: false
listed: true
branchIndependent: false
salvageExempted: true
bodyTagPinningExempted: false
parents: []
blueprint: unit_system
textType: 
livery: default
aiBehavior: 
aiTargeting: 
tags:
- type_system
- type_uncrewed
- type_flying
partTagPreferences: 
parts:
  core:
    livery: 
    preset: !PartResolverKeys
      keys:
      - vhc_drone_core_01
    rating: 
    systems: 
animationOverrides: 
effects:
  effectsOnSpawn:
  - checksGlobal: 
    checksBase: 
    checksPilot: 
    checksUnit: 
    functionsGlobal: 
    functionsBase: 
    functionsCombat: 
    functionsUnit:
    - !CombatUnitTagSet
      tags:
      - flag_uncollideable
      - flag_spike_one_hit
    functionsPilot: 
  effectsOnArrival: 
  effectProximity: 
  effectsOnEjection: 
  effectsOnDestruction: 
