hidden: false
listed: true
branchIndependent: true
salvageExempted: false
bodyTagPinningExempted: false
parents:
- key: vhc_mech
blueprint: 
textType: 
livery: 
aiBehavior: 
aiTargeting: juggernaut
tags:
- role_3f_squads
- role_3f_heavy
- weight_heavy
partTagPreferences:
  body:
  - tags:
      armor_full_weight_coverage: true
parts:
  back:
    livery: 
    preset: !PartResolverKeys
      keys:
      - back_wpn_ml_05
      - back_wpn_ml_04
      - back_wpn_ml_01
    rating: 
    systems: 
  core:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          weight_medium: true
    rating: 
    systems:
      internal_aux_top_core:
        livery: 
        flags: 
        resolver: !SubsystemResolverKeys
          keys:
          - internal_aux_core_heat
  equipment_left:
    livery: 
    preset: !PartResolverClear {}
    rating: 
    systems: 
  equipment_right:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          part_ballistic: true
          part_ultraheavy: true
          wpn_primary: true
    rating: 
    systems: 
  optional_left:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          weight_medium: true
    rating: 
    systems: 
  optional_right:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          weight_medium: true
    rating: 
    systems: 
  secondary:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          weight_heavy: true
    rating: 
    systems: 
animationOverrides: 
effects:
  effectsOnSpawn:
  - checksGlobal: 
    checksBase: 
    checksPilot: 
    checksUnit: 
    functionsGlobal: 
    functionsBase: 
    functionsCombat: 
    functionsUnit:
    - !CombatUnitSetSpeed
      mode: Set
      speed: 7.5
    functionsPilot: 
  effectsOnArrival: 
  effectProximity: 
  effectsOnEjection: 
  effectsOnDestruction: 
