hidden: false
listed: true
branchIndependent: true
salvageExempted: false
bodyTagPinningExempted: false
parents:
- key: vhc_tank_v2_w3
- key: vhc_tank_v2_wpn_adapter
blueprint: 
textType: 
livery: 
aiBehavior: 
aiTargeting: 
tags:
- range_long
- branches_blocked
partTagPreferences: 
parts:
  back:
    livery: 
    preset: !PartResolverKeys
      keys:
      - back_wpn_tank_ml_01
      - back_wpn_tank_defense_01
    rating: 
    systems: 
  equipment_right:
    livery: 
    preset: !PartResolverTags
      filters:
      - tags:
          part_ml: false
          range_medium: true
          type_incompatible: false
          wpn_primary: true
    rating: 
    systems: 
animationOverrides: 
effects:
  effectsOnSpawn:
  - checksGlobal: 
    checksBase: 
    checksPilot: 
    checksUnit: 
    functionsGlobal: 
    functionsBase: 
    functionsCombat: 
    functionsUnit:
    - !CombatUnitSetSpeed
      mode: Set
      speed: 9
    - !CombatUnitSetStatMultiplier
      key: heat_dissipation
      mode: Set
      value: 1.5
      refreshFullStats: true
    - !CombatUnitTagSet
      tags:
      - flag_scatter_stabilized
    functionsPilot: 
  effectsOnArrival: 
  effectProximity: 
  effectsOnEjection: 
  effectsOnDestruction: 
