actionID: 61
type: ButtonPositive
defaultValueKeyboard: 26
defaultValueMouse: -1
defaultValueGamepad: 9
buttonAsAxisGamepad: false
group: Global
subGroup: 0
priority: 6
visible: true
locked: false
visibleForMKB: true
visibleForGamepad: true
removableValueKeyboard: false
removableValueMouse: true
removableValueGamepad: false
invalidValuesKeyboard: 
