actionID: 41
type: ButtonPositive
defaultValueKeyboard: 71
defaultValueMouse: -1
defaultValueGamepad: 10
buttonAsAxisGamepad: false
group: Overworld
subGroup: 0
priority: 40
visible: true
locked: false
visibleForMKB: true
visibleForGamepad: true
removableValueKeyboard: false
removableValueMouse: true
removableValueGamepad: true
invalidValuesKeyboard:
- 97
