horizontal: false
extended: false
lines:
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_briefing_squad__s0
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_briefing_slot__s1
