horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_loadout_root__s0
- visibility: All
  actions:
  - action: global_confirm
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_loadout_root__s2
- visibility: All
  actions:
  - action: global_gamepad_x
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
