horizontal: true
extended: true
lines:
- visibility: Controller
  actions:
  - action: global_cancel
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
