horizontal: false
extended: false
lines:
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_briefing_squad__s0
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_briefing_slot__s1
- visibility: All
  actions:
  - action: global_gamepad_x
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_briefing_slot__s2
- visibility: All
  actions:
  - action: global_gamepad_y
    newline: false
  mode: LocReused
  text: 
  textSector: ui_base
  textKey: briefing_squad_edit_header
