horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  - action: global_direction_left
    newline: false
  - action: global_direction_right
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
- visibility: All
  actions:
  - action: global_confirm
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: base_loadout_sel__s3
