horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_pause
  textKey: root_button_back
- visibility: KeyboardMouse
  actions:
  - action: global_camera_zoom
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: combat_context_timeline__s3
- visibility: Controller
  actions:
  - action: overworld_tab_move_prev
    newline: false
  - action: overworld_tab_move_next
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: combat_context_timeline__s3
