horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: combat_time_toggle
    newline: false
  - action: global_confirm
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
