horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_pause
  textKey: root_button_back
- visibility: Controller
  actions:
  - action: global_confirm
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: generic_confirm_return__s0
- visibility: KeyboardMouse
  actions:
  - action: global_mouse_primary
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: generic_confirm_return__s0
