horizontal: false
extended: false
lines:
- visibility: KeyboardMouse
  actions:
  - action: global_move_vertical_pos
    newline: false
  - action: global_move_vertical_neg
    newline: false
  - action: global_move_horizontal_neg
    newline: false
  - action: global_move_horizontal_pos
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: overworld_campaign_map__s2
- visibility: Controller
  actions:
  - action: global_move_vertical
    newline: false
  - action: global_move_horizontal
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: overworld_campaign_map__s2
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: overworld_campaign_options__s2
- visibility: All
  actions:
  - action: global_direction_left
    newline: false
  - action: global_direction_right
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_pause
  textKey: root_button_back
