horizontal: false
extended: false
lines:
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: overworld_interaction_choice__s0
- visibility: All
  actions:
  - action: global_confirm
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: overworld_interaction_choice__s1
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_overworld
  textKey: int_sh_option_leave_header
