horizontal: false
extended: false
lines:
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_pause
  textKey: root_button_back
- visibility: All
  actions:
  - action: global_confirm
    newline: false
  mode: LocReused
  text: 
  textSector: ui_overworld
  textKey: lock_camp_selection_start
