horizontal: true
extended: false
lines:
- visibility: All
  actions:
  - action: global_direction_up
    newline: false
  - action: global_direction_down
    newline: false
  mode: LocUnique
  text: 
  textSector: 
  textKey: 
- visibility: All
  actions:
  - action: global_cancel
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: generic_return__s0
- visibility: All
  actions:
  - action: global_confirm
    newline: false
  mode: LocReused
  text: 
  textSector: ui_input_hints
  textKey: generic_confirm_return__s0
