hidden: false
parents: 
core:
  stepOnStart: main
  timeLocked: false
  time: 7
  scalingUsed: true
  loadImmediately: false
  externalBranchUsed: true
  externalLevelUsed: true
  reinforcementsUsed: false
  replayUsed: true
  unitLossUsed: true
  lootingUsed: true
  musicDynamic: false
  introUsed: true
  musicCustom: 
  introOverride: 
  briefingSpawnHighlights: 
  briefingGroupsInjected: 
  briefingUnitsInjected: 
  actionBlocklist: 
  customExitBehaviour: 
  weatherOverridePrecipitation: 
  weatherOverrideTemperature: 
  introSettings: 
  textIntroPrimary: 
  textIntroLocation: 
  textIntroThreat: 
  textIntroReady: 
  cameraStartingYawRotation: 
standalone: 
areas:
  tagFilterFromSite: true
  tagFilterUsed: true
  tagFilter:
    context_capture_loot: true
    type_main: true
  keys: 
entry:
  squadUsed: true
  squadSize: 4
  squadSlotCustom:
    spawnTagsUsed: true
    spawnTags:
      perimeter_outer: true
    spawnGroupKey: 
    filterDistancePlayer: 
    filterDistanceEnemy: 
    filterDistanceSpawn: 
    filterDistanceLocation: 
    filterDistanceVolume: 
    filterDistanceState: 
    filterDistanceRetreat: 
    sorting: 
    spawnRegistration: 
generationInjection: 
tags:
- context_generic
- trait_marathon
- trait_objectives
- type_entity_convoy_cargo
- type_raid
- context_contract
states:
  obj_01_detection:
    comment:
      comment: This state reacts for every turn a PB mech is not in a designated location.
    evaluated: true
    startInScope: true
    priorityGeneration: 10
    priority: 2
    briefingHidden: false
    ui: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks:
    - count:
        check: Equal
        value: 0
      exportCountToMemory: 
      exportEntitiesToBlackboard: 
      tags:
        in_state_obj_01_extraction: true
      name: 
      faction:
        key: Phantoms
      state: 
      actionPlanned: 
      locationOccupied: 
      locationOccupiedUnlinked: 
      relativeTransform: 
      blueprints: 
      classes: 
      stats: 
      statsNormalized: 
      actionsInProgress: 
      functions: 
    unitCheckLinked: 
    location: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: false
      effectsPerIncrement:
        0:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !ModifyMemoryBase
            changes:
            - change: Offset
              key: combat_sc_objective_progress_01
              value: 1
              valueFromMemory: false
              valueFromMemoryKey: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_01_disruption:
    comment:
      comment: This state reacts upon PB unit entering the location, visualizing disruption.
    evaluated: true
    startInScope: true
    priorityGeneration: 10
    priority: 1
    briefingHidden: false
    ui: 
    evaluationContext: OnLocationContact
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks:
    - count: 
      exportCountToMemory: 
      exportEntitiesToBlackboard: 
      tags:
        in_state_obj_01_extraction: true
      name: 
      faction:
        key: Phantoms
      state: 
      actionPlanned: 
      locationOccupied: 
      locationOccupiedUnlinked: 
      relativeTransform: 
      blueprints: 
      classes: 
      stats: 
      statsNormalized: 
      actionsInProgress: 
      functions: 
    unitCheckLinked: 
    location:
      visibleInWorld: true
      locationProvider: !AreaLocationFromState
        stateKey: obj_01_extraction
      visual: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: false
      effectsPerIncrement:
        0:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !CombatCreateCommsMessage
            time: 0
            key: generic_target_block_a
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_01_extraction:
    comment: 
    evaluated: true
    startInScope: true
    priorityGeneration: 0
    priority: 3
    briefingHidden: false
    ui:
      priorityDisplay: 3
      briefingHidden: false
      checkboxUsed: false
      progressInverted: false
      progressLimitHidden: false
      progressHiddenAtZero: false
      textHeader:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_01_header
      textDesc:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_text
      textHeaderCompleted:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_fail_text
      textDescCompleted: 
      mood:
        i: -2
      moodIntensityNormal: 
      moodIntensityProgress:
        f: 0.5
      progressLimitOverride: 
      progressLimitMemory: 
      progressSuffixSprite: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks: 
    unitCheckLinked: 
    location:
      visibleInWorld: false
      locationProvider: !AreaLocationFilter
        includeOverlaps: false
        tagRequirements:
          obj_loot: true
        filters: 
      visual:
        key: obj_prop_loot_01
        reactionAnimation: true
    locationRetreat: 
    volume: 
    stateValues:
      outcome_victory: false
    memoryBase:
      method: RequireAll
      checks:
      - key: combat_sc_objective_progress_01
        presenceDesired: true
        valueFromMemory: false
        valueFromMemoryKey: 
        valueCheck: GreaterEqual
        value: 4
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: false
      triggerLimit: 1
      triggerIncrement: true
      effectsPerIncrement:
        1:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart:
          - time: 0
            hidden: false
            key: generic_raid_obj_extracted_one
            functionsOnExit: 
          memoryChanges: 
          stateScopeChanges:
            obj_01_detection: false
            obj_01_disruption: false
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !ModifyMemoryBase
            changes:
            - change: Offset
              key: combat_sc_targets_lost
              value: 1
              valueFromMemory: false
              valueFromMemoryKey: 
          - !CombatCreateStrike
            delay: 0
            blueprintKey: aircraft_airlift
            target:
              type: State
              name: obj_01_extraction
              center: true
              modifiersDirectional: false
              modifiers: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_02_detection:
    comment:
      comment: This state reacts for every turn a PB mech is not in a designated location.
    evaluated: true
    startInScope: true
    priorityGeneration: 10
    priority: 2
    briefingHidden: false
    ui: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks:
    - count:
        check: Equal
        value: 0
      exportCountToMemory: 
      exportEntitiesToBlackboard: 
      tags:
        in_state_obj_02_extraction: true
      name: 
      faction:
        key: Phantoms
      state: 
      actionPlanned: 
      locationOccupied: 
      locationOccupiedUnlinked: 
      relativeTransform: 
      blueprints: 
      classes: 
      stats: 
      statsNormalized: 
      actionsInProgress: 
      functions: 
    unitCheckLinked: 
    location: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: false
      effectsPerIncrement:
        0:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !ModifyMemoryBase
            changes:
            - change: Offset
              key: combat_sc_objective_progress_02
              value: 1
              valueFromMemory: false
              valueFromMemoryKey: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_02_disruption:
    comment:
      comment: This state reacts upon PB unit entering the location, visualizing disruption.
    evaluated: true
    startInScope: true
    priorityGeneration: 10
    priority: 1
    briefingHidden: false
    ui: 
    evaluationContext: OnLocationContact
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks:
    - count: 
      exportCountToMemory: 
      exportEntitiesToBlackboard: 
      tags:
        in_state_obj_02_extraction: true
      name: 
      faction:
        key: Phantoms
      state: 
      actionPlanned: 
      locationOccupied: 
      locationOccupiedUnlinked: 
      relativeTransform: 
      blueprints: 
      classes: 
      stats: 
      statsNormalized: 
      actionsInProgress: 
      functions: 
    unitCheckLinked: 
    location:
      visibleInWorld: true
      locationProvider: !AreaLocationFromState
        stateKey: obj_02_extraction
      visual: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: false
      effectsPerIncrement:
        0:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !CombatCreateCommsMessage
            time: 0
            key: generic_target_block_b
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_02_extraction:
    comment: 
    evaluated: true
    startInScope: true
    priorityGeneration: 0
    priority: 3
    briefingHidden: false
    ui:
      priorityDisplay: 3
      briefingHidden: false
      checkboxUsed: false
      progressInverted: false
      progressLimitHidden: false
      progressHiddenAtZero: false
      textHeader:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_02_header
      textDesc:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_text
      textHeaderCompleted:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_raid_obj_fail_text
      textDescCompleted: 
      mood:
        i: -2
      moodIntensityNormal: 
      moodIntensityProgress:
        f: 0.5
      progressLimitOverride: 
      progressLimitMemory: 
      progressSuffixSprite: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks: 
    unitCheckLinked: 
    location:
      visibleInWorld: false
      locationProvider: !AreaLocationFilter
        includeOverlaps: false
        tagRequirements:
          obj_loot: true
        filters: 
      visual:
        key: obj_prop_loot_01
        reactionAnimation: true
    locationRetreat: 
    volume: 
    stateValues:
      outcome_victory: false
    memoryBase:
      method: RequireAll
      checks:
      - key: combat_sc_objective_progress_02
        presenceDesired: true
        valueFromMemory: false
        valueFromMemoryKey: 
        valueCheck: GreaterEqual
        value: 6
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: false
      triggerLimit: 1
      triggerIncrement: true
      effectsPerIncrement:
        1:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart:
          - time: 0
            hidden: false
            key: generic_raid_obj_extracted_one
            functionsOnExit: 
          memoryChanges: 
          stateScopeChanges:
            obj_02_detection: false
            obj_02_disruption: false
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions:
          - !ModifyMemoryBase
            changes:
            - change: Offset
              key: combat_sc_targets_lost
              value: 1
              valueFromMemory: false
              valueFromMemoryKey: 
          - !CombatCreateStrike
            delay: 0
            blueprintKey: aircraft_airlift
            target:
              type: State
              name: obj_02_extraction
              center: true
              modifiersDirectional: false
              modifiers: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome: 
  obj_fail:
    comment:
      comment: This state has negative priority to ensure it only returns true next turn after all cargo is extracted. It ends combat if player fails to stop every extraction.
    evaluated: true
    startInScope: true
    priorityGeneration: -1
    priority: -1
    briefingHidden: false
    ui: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn: 
    turnModulus: 
    unitChecks: 
    unitCheckLinked: 
    location: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase:
      method: RequireAll
      checks:
      - key: combat_sc_targets_lost
        presenceDesired: true
        valueFromMemory: true
        valueFromMemoryKey: combat_sc_targets_spawned
        valueCheck: GreaterEqual
        value: 0
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: true
      effectsPerIncrement:
        1:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart:
          - time: 0
            hidden: false
            key: generic_raid_obj_extracted_all
            functionsOnExit: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome:
            type: Defeat
            early: true
            instant: false
  outcome_victory:
    comment: 
    evaluated: true
    startInScope: true
    priorityGeneration: 50
    priority: 50
    briefingHidden: false
    ui: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome:
      present: false
    turn: 
    turnModulus: 
    unitChecks:
    - count:
        check: Equal
        value: 0
      exportCountToMemory: 
      exportEntitiesToBlackboard: 
      tags: 
      name: 
      faction:
        key: Invaders
      state: 
      actionPlanned: 
      locationOccupied: 
      locationOccupiedUnlinked: 
      relativeTransform: 
      blueprints: 
      classes: 
      stats: 
      statsNormalized: 
      actionsInProgress: 
      functions: 
    unitCheckLinked: 
    location: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: true
      effectsPerIncrement:
        1:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions: 
          functionsPerUnit: 
          unitGroups: 
          unitGeneratorKeys: 
          outcome:
            type: Victory
            early: false
            instant: false
  reinforcements:
    comment: 
    evaluated: true
    startInScope: true
    priorityGeneration: 20
    priority: 20
    briefingHidden: false
    ui:
      priorityDisplay: 50
      briefingHidden: false
      checkboxUsed: false
      progressInverted: false
      progressLimitHidden: false
      progressHiddenAtZero: false
      textHeader:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_enemy_reinforcements_header
      textDesc:
        mode: LocReused
        text: 
        textSector: scenario_states_shared
        textKey: generic_enemy_reinforcements_text
      textHeaderCompleted: 
      textDescCompleted: 
      mood: 
      moodIntensityNormal: 
      moodIntensityProgress: 
      progressLimitOverride: 
      progressLimitMemory: 
      progressSuffixSprite: 
    evaluationContext: OnExecutionEnd
    evaluationOnOutcome: 
    turn:
      relative: false
      check: GreaterEqual
      value: 3
    turnModulus: 
    unitChecks: 
    unitCheckLinked: 
    location: 
    locationRetreat: 
    volume: 
    stateValues: 
    memoryBase: 
    functions: 
    reactions:
      expectedValue: true
      scopeRemovalOnLimit: true
      triggerLimit: 1
      triggerIncrement: true
      effectsPerIncrement:
        1:
          tags: 
          executionOnOutcome: 
          stepTransition: 
          commsOnStart: 
          memoryChanges: 
          stateScopeChanges: 
          stateValueChanges: 
          memoryDisplayChanges: 
          unitTagDisplayChanges: 
          rewards: 
          functions: 
          functionsPerUnit: 
          unitGroups:
          - !UnitGroupFilter
            tagsFromFactionBranch: true
            tags:
              weight_heavy: false
            check: 
            combatTags: 
            spawnGroupOccupied: true
            spawnCountStrict: true
            spawnOrderRandom: true
            factionBranchOverride: false
            factionBranchKey: 
            baseGrade: 0
            maxGrade: 1
            cloneable: false
            functions: 
            spawnTagsUsed: true
            spawnTags:
              perimeter_outer: true
            spawnGroupKey: 
            filterDistancePlayer: 
            filterDistanceEnemy: 
            filterDistanceSpawn: 
            filterDistanceLocation: 
            filterDistanceVolume: 
            filterDistanceState: 
            filterDistanceRetreat: 
            sorting: 
            spawnRegistration: 
          unitGeneratorKeys: 
          outcome: 
steps:
  main:
    comment: 
    core:
      color:
        r: 1
        g: 1
        b: 1
        a: 1
      textHeader:
        mode: LocReused
        text: 
        textSector: scenario_groups
        textKey: type_raid__name
      textDesc:
        mode: LocReused
        text: 
        textSector: scenario_embedded
        textKey: generic_raid__step_main_0c_text
      threatRatingPercentage: 1
      allowOutcomeVictory: false
      allowOutcomeDefeat: true
      executionAllowed: true
      visible: true
    tags:
    - start
    unitGroups:
    - !UnitGroupFilter
      tagsFromFactionBranch: true
      tags:
        range_medium: true
        weight_heavy: false
      check: 
      combatTags: 
      spawnGroupOccupied: true
      spawnCountStrict: true
      spawnOrderRandom: true
      factionBranchOverride: false
      factionBranchKey: 
      baseGrade: 0
      maxGrade: 2
      cloneable: false
      functions: 
      spawnTagsUsed: true
      spawnTags:
        perimeter_center: true
      spawnGroupKey: 
      filterDistancePlayer: 
      filterDistanceEnemy: 
      filterDistanceSpawn: 
      filterDistanceLocation: 
      filterDistanceVolume: 
      filterDistanceState:
        key: obj_01_extraction
        check: Greater
        value: 30
      filterDistanceRetreat: 
      sorting: !UnitSlotSortingState
        key: obj_01_extraction
        invert: true
      spawnRegistration: 
    - !UnitGroupFilter
      tagsFromFactionBranch: true
      tags:
        type_main: true
        weight_heavy: true
      check:
        log: false
        stateRequirements: 
        checksGlobal:
        - !OverworldValidateModifier
          key: sp_liberation_easy
          present: false
        checksBase: 
        checksTarget: 
        checksProvince: 
      combatTags: 
      spawnGroupOccupied: true
      spawnCountStrict: true
      spawnOrderRandom: true
      factionBranchOverride: false
      factionBranchKey: 
      baseGrade: 0
      maxGrade: 2
      cloneable: false
      functions: 
      spawnTagsUsed: true
      spawnTags:
        perimeter_center: true
      spawnGroupKey: 
      filterDistancePlayer: 
      filterDistanceEnemy: 
      filterDistanceSpawn: 
      filterDistanceLocation: 
      filterDistanceVolume: 
      filterDistanceState:
        key: obj_02_extraction
        check: Greater
        value: 30
      filterDistanceRetreat: 
      sorting: !UnitSlotSortingState
        key: obj_02_extraction
        invert: true
      spawnRegistration: 
    unitGeneratorKeys: 
    stateScopeChanges: 
    stateValueChanges: 
    memoryDisplayChanges: 
    unitTagDisplayChanges: 
    unitChanges: 
    retreat:
      stateKey: retreat_default
      stateValueModified: true
      stateValue: false
    actionRestrictions: 
    cutsceneVideoOnStart: 
    atmosphereOnStart: 
    hintsConditional: 
    unitSelection: 
    camera: 
    musicMood: 
    musicIntensity: 
    musicReactive: 
    commsOnStart:
    - time: 0
      hidden: false
      key: generic_raid_start
      functionsOnExit: 
    audioEventsOnStart: 
    audioStatesOnStart: 
    audioSyncsOnStart: 
    functions:
    - !ClearBaseCombatMemory {}
    - !ModifyMemoryBase
      changes:
      - change: Set
        key: combat_sc_targets_spawned
        value: 2
        valueFromMemory: false
        valueFromMemoryKey: 
    outcome: 
    transitions: 
unitPresets: 
unitGenerators: 
