hidden: false
parents:
- key: generic_elimination
core: 
standalone: 
areas: 
entry: 
generationInjection: 
tags:
- context_contract
states: 
steps:
  main:
    comment: 
    core: 
    tags: 
    unitGroups: 
    unitGeneratorKeys: 
    stateScopeChanges: 
    stateValueChanges: 
    memoryDisplayChanges: 
    unitTagDisplayChanges: 
    unitChanges: 
    retreat: 
    actionRestrictions: 
    cutsceneVideoOnStart: 
    atmosphereOnStart: 
    hintsConditional: 
    unitSelection: 
    camera: 
    musicMood: 
    musicIntensity: 
    musicReactive: 
    commsOnStart:
    - time: 0
      hidden: false
      key: generic_elimination_start_normal
      functionsOnExit: 
    audioEventsOnStart: 
    audioStatesOnStart: 
    audioSyncsOnStart: 
    functions: 
    outcome: 
    transitions: 
unitPresets: 
unitGenerators: 
