timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: Leveltest
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: Verträge
    textEng: Contracts
  replay__name:
    id: 2
    text: Kampagne
    textEng: Campaign
  training__name:
    id: 2
    text: Schulung
    textEng: Training
