timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: Einfacher Vertrag
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: Mittlerer Vertrag
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: Schwieriger Vertrag
    textEng: Challenging contract
