timeLastSync: 0
entries:
  dev_areas_listed__name:
    id: 2
    text: 等級測試
    textEng: Area testing
  gen_contracts__name:
    id: 2
    text: 合約
    textEng: Contracts
  replay__name:
    id: 2
    text: 戰役
    textEng: Campaign
  training__name:
    id: 2
    text: 訓練
    textEng: Training
