timeLastSync: 0
entries:
  contract_generic_01_list:
    id: 2
    text: 簡單合約
    textEng: Easy contract
  contract_generic_02_list:
    id: 2
    text: 中等合約
    textEng: Medium contract
  contract_generic_03_list:
    id: 2
    text: 高難度合約
    textEng: Challenging contract
