timeLastSync: 63817552341
entries:
  base_briefing_list__s0:
    id: 2
    text: 返回小隊
    textEng: Return to squad
  base_briefing_list__s1:
    id: 2
    text: 新增或移除
    textEng: Add or remove
  base_briefing_slot__s1:
    id: 2
    text: 進入列表
    textEng: Enter list
  base_briefing_slot__s2:
    id: 2
    text: 清除槽位
    textEng: Clear slot
  base_briefing_squad__s0:
    id: 2
    text: 返回劇情
    textEng: Return to scenario
  base_briefing_squad_list__s1:
    id: 2
    text: 跳至列表
    textEng: Jump to list
  base_context_item_selector__s0:
    id: 1
    text: 複選
    textEng: Multi-select
  base_general__header:
    id: 1
    text: 移動基地
    textEng: Mobile base
  base_general__overview:
    id: 1
    text: 管理你的駕駛員、單位與物品清單。將資源投資在工作坊計畫或是升級基地。當你準備好繼續戰役的時候返回主世界地圖。
    textEng: Manage your pilots, units and inventory. Invest resources into workshop projects or base upgrades. Return to the overworld map when you're ready to continue your campaign.
  base_general__s2:
    id: 1
    text: 瀏覽
    textEng: Navigate
  base_general__s3:
    id: 1
    text: 世界地圖
    textEng: World map
  base_general__s4:
    id: 1
    text: 駕駛員列表
    textEng: Pilot list
  base_general__s5:
    id: 1
    text: 單位列表
    textEng: Unit list
  base_general__s6:
    id: 1
    text: 倉庫
    textEng: Inventory
  base_general__s7:
    id: 1
    text: 工作坊
    textEng: Workshop
  base_general__s8:
    id: 1
    text: 升級
    textEng: Upgrades
  base_inventory_context__s0:
    id: 2
    text: 返回列表
    textEng: Return to list
  base_inventory_root__s0:
    id: 2
    text: 選擇類別
    textEng: Select category
  base_inventory_root__s1:
    id: 2
    text: 開啟類別
    textEng: Open category
  base_inventory_sel__s0:
    id: 2
    text: 移動
    textEng: Move
  base_inventory_sel__s1:
    id: 2
    text: 選擇物品
    textEng: Select item
  base_inventory_sel__s2:
    id: 2
    text: 背景選單
    textEng: Context menu
  base_loadout_livery_grid__s0:
    id: 2
    text: 瀏覽
    textEng: Navigate
  base_loadout_livery_grid__s1:
    id: 2
    text: 切換塗裝
    textEng: Toggle livery
  base_loadout_livery_nav__s2:
    id: 2
    text: 清除槽位
    textEng: Clear slot
  base_loadout_role__s0:
    id: 2
    text: 移動
    textEng: Move
  base_loadout_role__s1:
    id: 2
    text: 選擇圖示
    textEng: Select icon
  base_loadout_root__s0:
    id: 2
    text: 選擇槽位
    textEng: Select slot
  base_loadout_root__s1:
    id: 2
    text: 開啟槽位
    textEng: Open slot
  base_loadout_root__s2:
    id: 2
    text: 清除槽位
    textEng: Clear slot
  base_loadout_sel__s0:
    id: 2
    text: 選擇物品
    textEng: Select item
  base_loadout_sel__s1:
    id: 2
    text: 裝備
    textEng: Equip
  base_loadout_sel__s2:
    id: 2
    text: 返回槽位
    textEng: Return to slots
  base_loadout_sel_filter__s0:
    id: 2
    text: 套用篩選
    textEng: Apply filter
  base_upgrades_grid__overview:
    id: 2
    text: 瀏覽升級項目網格
    textEng: Navigating upgrade grid
  base_upgrades_grid__s0:
    id: 2
    text: 捲動
    textEng: Scroll
  base_upgrades_grid__s2:
    id: 2
    text: 在升級項目間切換
    textEng: Jump between upgrades
  base_upgrades_grid__s3:
    id: 2
    text: 跳至狀態數值
    textEng: Jump to stats
  base_upgrades_sidebar__overview:
    id: 2
    text: 選定側邊欄
    textEng: Sidebar in focus
  base_upgrades_sidebar__s0:
    id: 2
    text: 返回升級頁面
    textEng: Return to upgrades
  base_upgrades_sidebar__s1:
    id: 2
    text: 選擇狀態數值
    textEng: Select stats
  combat_action_melee__s3:
    id: 2
    text: 交換方向
    textEng: Swap direction
  combat_action_targeting_swap__s3:
    id: 2
    text: 鎖定模式
    textEng: Target mode
  combat_action_targeting_swap__s5:
    id: 2
    text: 微調高度
    textEng: Nudge height
  combat_context_comms__s0:
    id: 1
    text: 跳過對話
    textEng: Skip dialogue
  combat_context_nav__overview:
    id: 2
    text: 選定瀏覽
    textEng: Navigation in focus
  combat_context_nav__s1:
    id: 2
    text: 選擇單位
    textEng: Select units
  combat_context_nav__s3:
    id: 2
    text: 變更時間
    textEng: Change time
  combat_context_timeline__overview:
    id: 2
    text: 選定時間軸
    textEng: Timeline in focus
  combat_context_timeline__s1:
    id: 2
    text: 刪除動作
    textEng: Delete action
  combat_context_timeline__s3:
    id: 2
    text: 拖曳動作
    textEng: Drag action
  combat_general__header:
    id: 1
    text: 戰鬥
    textEng: Combat
  combat_general__overview:
    id: 1
    text: 跟從畫面右上角的目標來贏得戰鬥。重複查看預測的敵方行動，使用時間軸對你的單位下達指令，並且執行指令來觀看計畫展開。
    textEng: Follow the objectives in the top right corner to win the fight. Review the predicted enemy actions, give orders to your units using the timeline, and execute to watch the plan unfold.
  combat_general__s0:
    id: 1
    text: 返回／取消
    textEng: Back / Cancel
  combat_general__s1:
    id: 1
    text: 確認／執行
    textEng: Confirm / Execute
  combat_general__s10:
    id: 2
    text: 切換慢動作
    textEng: Toggle slow motion
  combat_general__s2:
    id: 1
    text: 瀏覽
    textEng: Navigate
  combat_general__s3:
    id: 1
    text: 移動鏡頭
    textEng: Move camera
  combat_general__s4:
    id: 1
    text: 旋轉鏡頭
    textEng: Rotate camera
  combat_general__s5:
    id: 1
    text: 選取下一個單位
    textEng: Select next unit
  combat_general__s6:
    id: 1
    text: 選取上一個單位
    textEng: Select previous unit
  combat_general__s7:
    id: 1
    text: 鎖定模式
    textEng: Targeting mode
  combat_general__s8:
    id: 1
    text: 選擇動作
    textEng: Select action
  combat_general__s9:
    id: 2
    text: 設定時間倍率
    textEng: Set time scale
  combat_root_execution__s7:
    id: 2
    text: 切換慢動作
    textEng: Toggle slow motion
  combat_root_execution__s9:
    id: 2
    text: 選定時間控制
    textEng: Focus time controls
  combat_root_planning__s0:
    id: 2
    text: 執行
    textEng: Execute
  combat_root_planning__s1:
    id: 2
    text: 執行
    textEng: Execute
  combat_root_planning__s10:
    id: 2
    text: 跳至時間軸
    textEng: Jump to timeline
  combat_root_planning__s11:
    id: 2
    text: 跳至動作
    textEng: Jump to actions
  combat_root_planning__s12:
    id: 2
    text: 跳至移動
    textEng: Jump to movement
  combat_root_planning__s4:
    id: 2
    text: 移除動作
    textEng: Remove actions
  combat_root_planning__s5:
    id: 2
    text: 縮放鏡頭
    textEng: Zoom camera
  combat_root_planning__s6:
    id: 2
    text: 切換單位
    textEng: Switch unit
  combat_root_planning__s8:
    id: 2
    text: 切換詳細資訊
    textEng: Toggle details
  combat_root_planning__s9:
    id: 2
    text: 顯示詳細資訊
    textEng: Show details
  combat_test_zoom__s0:
    id: 2
    text: 縮放測試
    textEng: Zoom test
  credits__s0:
    id: 2
    text: 離開
    textEng: Exit
  credits__s1:
    id: 2
    text: 捲動
    textEng: Scroll
  general_skip__s0:
    id: 2
    text: 跳過動畫
    textEng: Skip animation
  generic_confirm_return__s0:
    id: 1
    text: 確認
    textEng: Confirm
  generic_return__s0:
    id: 2
    text: 返回
    textEng: Return
  overworld_campaign_map__s0:
    id: 2
    text: 選擇省份
    textEng: Select province
  overworld_campaign_map__s2:
    id: 2
    text: 移動地圖
    textEng: Move map
  overworld_campaign_options__s2:
    id: 2
    text: 選取選項
    textEng: Select option
  overworld_campaign_options_mods__s3:
    id: 2
    text: 檢視修改器
    textEng: Inspect modifiers
  overworld_codex__s1:
    id: 2
    text: 捲動
    textEng: Scroll
  overworld_general__header:
    id: 1
    text: 主世界
    textEng: Overworld
  overworld_general__overview:
    id: 1
    text: 在地圖上移動、參加遊戲事件、攻擊敵軍地點。爭奪省份並且驅逐入侵勢力。利用移動基地來管理單位、駕駛員與加強升級。
    textEng: Navigate the map, participate in events, attack hostile sites. Contest provinces and drive the invasion forces out. Use the mobile base to manage units, pilots and upgrades.
  overworld_general__s2:
    id: 1
    text: 瀏覽
    textEng: Navigate
  overworld_general__s3:
    id: 1
    text: 在地圖上選擇
    textEng: Select on the map
  overworld_general__s4:
    id: 1
    text: 移動基地
    textEng: Move the base
  overworld_general__s5:
    id: 2
    text: 移動鏡頭
    textEng: Move camera
  overworld_general__s6:
    id: 2
    text: 旋轉鏡頭
    textEng: Rotate camera
  overworld_general__s7:
    id: 2
    text: 切換暫停
    textEng: Toggle pause
  overworld_interaction_choice__s0:
    id: 2
    text: 選取選項
    textEng: Select option
  overworld_interaction_choice__s1:
    id: 2
    text: 確認
    textEng: Confirm
  overworld_roster_root__s0:
    id: 2
    text: 選取
    textEng: Select
  overworld_roster_root__s1:
    id: 2
    text: 移動
    textEng: Move
  overworld_roster_root__s2:
    id: 2
    text: 返回
    textEng: Return
  overworld_roster_root__s3:
    id: 2
    text: 移動
    textEng: Move
  overworld_roster_root__s4:
    id: 2
    text: 返回／停止
    textEng: Return / Stop
  overworld_roster_root__s5:
    id: 2
    text: 切換時間
    textEng: Toggle time
  overworld_roster_root__s7:
    id: 2
    text: 選取
    textEng: Select
  pause_difficulty_option__s0:
    id: 2
    text: 選取選項
    textEng: Select option
  pause_difficulty_option__s1:
    id: 2
    text: 變更選項
    textEng: Change option
  pause_difficulty_preset__s0:
    id: 2
    text: 選擇預設
    textEng: Select preset
  pause_difficulty_preset__s1:
    id: 2
    text: 套用預設
    textEng: Apply preset
  pause_difficulty_preset__s2:
    id: 2
    text: 跳至選項
    textEng: Jump to options
  pause_options_group__s0:
    id: 1
    text: 選擇類別
    textEng: Select group
  pause_options_group__s1:
    id: 1
    text: 進入類別
    textEng: Enter group
  pause_options_group__s2:
    id: 1
    text: 離開選項
    textEng: Exit options
  pause_options_input1__s0:
    id: 1
    text: 選擇選項
    textEng: Select option
  pause_options_input1__s1:
    id: 1
    text: 選擇按鍵綁定
    textEng: Select binding
  pause_options_input1__s2:
    id: 1
    text: 套用或重置
    textEng: Apply or reset
  pause_options_input1__s3:
    id: 1
    text: 返回類別
    textEng: Return to groups
  pause_options_input2__s0:
    id: 1
    text: 變更按鍵綁定
    textEng: Change binding
  pause_options_input2__s1:
    id: 1
    text: 返回
    textEng: Return
  pause_options_option__s0:
    id: 1
    text: 選擇選項
    textEng: Select option
  pause_options_option__s1:
    id: 1
    text: 變更選項
    textEng: Change option
  pause_options_option__s2:
    id: 1
    text: 套用或重置
    textEng: Apply or reset
  pause_options_option__s3:
    id: 1
    text: 返回類別
    textEng: Return to groups
  pause_root__s0:
    id: 2
    text: 瀏覽
    textEng: Navigate
